package authz

import (
	"fmt"
	"slices"
	"strings"

	"github.com/prokopto-dev/tod-serve/internal/schemaenum"
)

// ScopeEnumName is the enum name the PAT scope value set is generated under. Whether a token's
// scopes end up as a JSON column or a join table is the schema's business; either way these are
// the values, and they come from here.
const ScopeEnumName = "api_token.scope"

// ScopeEnum returns the PAT scope value set as an enum, so the CHECK constraint and the OpenAPI
// enum are rendered by the same code that renders every other enum in the schema.
func ScopeEnum() schemaenum.Enum {
	values := make([]string, 0, len(Scopes()))
	for _, def := range Scopes() {
		values = append(values, string(def.Key))
	}
	return schemaenum.Enum{Name: ScopeEnumName, Values: values}
}

// RolesFor returns the roles that grant p, weakest first.
func RolesFor(p Permission) []Role {
	var roles []Role
	for _, r := range Roles() {
		if RolePermissions(r).Has(p) {
			roles = append(roles, r)
		}
	}
	return roles
}

// ScopesFor returns the scopes that can reach p, in catalogue order. An empty result means no
// token reaches it at any scope.
func ScopesFor(p Permission) []Scope {
	var scopes []Scope
	for _, def := range Scopes() {
		if slices.Contains(def.Grants, p) {
			scopes = append(scopes, def.Key)
		}
	}
	return scopes
}

// OpenAPIPermission is the `x-tod-permission` extension attached to an operation, and the
// machine-readable half of what the documentation page says.
//
// It is a struct rather than a map[string]any because a generated spec that nobody can typecheck
// is a spec that drifts silently, and because `any` has no place in a signature here.
type OpenAPIPermission struct {
	Key            string   `json:"key"`
	Realm          string   `json:"realm"`
	RequiresStepUp bool     `json:"requires_step_up"`
	Roles          []string `json:"roles"`
	Scopes         []string `json:"scopes"`
	Summary        string   `json:"summary"`
}

// OpenAPIPermissions returns the extension metadata for every permission, in catalogue order.
func OpenAPIPermissions() []OpenAPIPermission {
	out := make([]OpenAPIPermission, 0, len(Permissions()))
	for _, def := range Permissions() {
		roles := []string{}
		for _, r := range RolesFor(def.Key) {
			roles = append(roles, string(r))
		}
		scopes := []string{}
		for _, s := range ScopesFor(def.Key) {
			scopes = append(scopes, string(s))
		}
		out = append(out, OpenAPIPermission{
			Key:            string(def.Key),
			Realm:          string(def.Realm),
			RequiresStepUp: def.StepUp,
			Roles:          roles,
			Scopes:         scopes,
			Summary:        def.Summary,
		})
	}
	return out
}

// generatedBy is the header every generated artefact carries. Without it, the first person to find
// a mistake in a generated file fixes the file.
const generatedBy = "internal/authz"

// regenerateCommand is how the generated page is rewritten. It is in the page itself, because the
// first person to find a mistake in a generated file otherwise fixes the file.
const regenerateCommand = "go test ./internal/authz -run TestPermissionsDoc -update"

// SeedSQL renders the `permission` and `role_permission` seeds.
//
// `role_permission` is FK-constrained to `permission(key)`, which is what makes a divergent
// hand-written list a boot failure rather than a subtle authorization bug. Rows are ordered by key
// so a regenerated seed diffs cleanly.
func SeedSQL() string {
	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by %s. Do not edit.\n", generatedBy)
	b.WriteString("-- The authorization catalogue: canonical conventions §6.\n\n")

	defs := slices.Clone(Permissions())
	slices.SortFunc(defs, func(a, c PermissionDef) int { return strings.Compare(string(a.Key), string(c.Key)) })

	b.WriteString("INSERT INTO permission (key, realm, requires_step_up, summary) VALUES\n")
	rows := make([]string, 0, len(defs))
	for _, def := range defs {
		rows = append(rows, fmt.Sprintf("  (%s, %s, %d, %s)",
			sqlQuote(string(def.Key)), sqlQuote(string(def.Realm)), boolToInt(def.StepUp),
			sqlQuote(def.Summary)))
	}
	b.WriteString(strings.Join(rows, ",\n"))
	b.WriteString(";\n\nINSERT INTO role_permission (role, permission_key) VALUES\n")

	rows = rows[:0]
	for _, r := range Roles() {
		for _, p := range RolePermissions(r).Slice() {
			rows = append(rows, fmt.Sprintf("  (%s, %s)", sqlQuote(string(r)), sqlQuote(string(p))))
		}
	}
	b.WriteString(strings.Join(rows, ",\n"))
	b.WriteString(";\n")
	return b.String()
}

// sqlQuote renders a SQL string literal. Every value passed to it is a catalogue constant, so this
// is not a sanitiser and must never be used as one; it exists so an apostrophe in a summary does
// not produce a seed that will not parse.
func sqlQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

// boolToInt renders a boolean the way the schema stores one: INTEGER, CHECK (x IN (0,1)).
func boolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

// PermissionsDoc renders docs/reference/permissions.md.
//
// A generated page is cheap and it proves the generator runs; a hand-written one is a fourth copy
// of the catalogue that goes stale the first time a permission is added in a hurry.
func PermissionsDoc() string {
	var b strings.Builder
	b.WriteString("# Permissions, scopes and roles\n\n")
	fmt.Fprintf(&b, "<!-- Generated by %s. Do not edit: regenerate with `%s`. -->\n\n",
		generatedBy, regenerateCommand)
	b.WriteString("**Status:** generated from `internal/authz/catalogue.go`. " +
		"**Tie-breaker:** [canonical conventions §6](../design/00-canonical-conventions.md#6-permissions-and-scopes--one-catalogue-generated).\n\n")
	b.WriteString("Effective capability is **role permissions ∩ token scopes**. " +
		"A permission narrows a role; a scope narrows a token. " +
		"There is no `admin:*` scope and no all-powerful token.\n\n")

	b.WriteString("## Permissions\n\n")
	b.WriteString("A permission with no scope is session-only: no token reaches it at any scope. " +
		"A permission marked step-up also requires re-authentication.\n\n")
	b.WriteString("| Permission | Realm | Roles | Scopes | Step-up | What it allows |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, def := range Permissions() {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s |\n",
			def.Key, def.Realm, joinRoles(RolesFor(def.Key)), joinScopes(ScopesFor(def.Key)),
			tick(def.StepUp), def.Summary)
	}

	b.WriteString("\n## The role matrix\n\n")
	b.WriteString("Cumulative: every role holds everything the role below it holds. " +
		"Instance-realm permissions are granted at the instance level and appear in no row.\n\n")
	b.WriteString("| Permission |")
	for _, r := range Roles() {
		fmt.Fprintf(&b, " %s |", r)
	}
	b.WriteString("\n|---|")
	for range Roles() {
		b.WriteString("---|")
	}
	b.WriteString("\n")
	for _, def := range Permissions() {
		if def.Realm != RealmCircle {
			continue
		}
		fmt.Fprintf(&b, "| `%s` |", def.Key)
		for _, r := range Roles() {
			fmt.Fprintf(&b, " %s |", tick(RolePermissions(r).Has(def.Key)))
		}
		b.WriteString("\n")
	}

	b.WriteString("\n## PAT scopes\n\n")
	b.WriteString("| Scope | Grants | What it is for |\n|---|---|---|\n")
	for _, def := range Scopes() {
		granted := make([]string, 0, len(def.Grants))
		for _, p := range def.Grants {
			granted = append(granted, "`"+string(p)+"`")
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", def.Key, strings.Join(granted, ", "), def.Summary)
	}

	b.WriteString("\n## The capability floor\n\n")
	b.WriteString("Session and step-up only. No PAT scope reaches any of these, " +
		"and `TestCapabilityFloor_MatchesCanonicalConventions` compares this list " +
		"against the canonical conventions in both directions.\n\n")
	for _, p := range CapabilityFloor() {
		fmt.Fprintf(&b, "- `%s`\n", p)
	}

	b.WriteString("\n### Not in the floor, deliberately\n\n")
	b.WriteString("`invite.create` is reachable by a token while `token.mint` is not. " +
		"An invite is time-boxed, single-use, role-capped below `owner` and fully audited, " +
		"so a leaked bot token can add a visible, revocable member — not seize the circle. " +
		"A minted PAT has none of those properties.\n")
	return b.String()
}

func joinRoles(roles []Role) string {
	if len(roles) == 0 {
		return "—"
	}
	parts := make([]string, 0, len(roles))
	for _, r := range roles {
		parts = append(parts, "`"+string(r)+"`")
	}
	return strings.Join(parts, ", ")
}

func joinScopes(scopes []Scope) string {
	if len(scopes) == 0 {
		return "—"
	}
	parts := make([]string, 0, len(scopes))
	for _, s := range scopes {
		parts = append(parts, "`"+string(s)+"`")
	}
	return strings.Join(parts, ", ")
}

func tick(b bool) string {
	if b {
		return "yes"
	}
	return "—"
}
