// Generated by internal/dbschema from the enum catalogue in internal/schemaenum.
// Do not edit: regenerate with `make gen`.
//
// Canonical conventions §5: the wire value is the database value, and both the
// SQL CHECK and the OpenAPI enum come from one Go catalogue. db/schema.hcl refers
// to these by name so that no value list is written twice.

locals {
  check_circle_server                     = "server IN ('blue', 'green', 'red')"
  check_circle_state                      = "state IN ('active', 'archived')"
  check_circle_timer_override_window_kind = "window_kind IN ('fixed', 'variance', 'unknown')"
  check_identity_link_method              = "method IN ('officer_asserted', 'provider_verified')"
  check_identity_provider_kind            = "kind IN ('discord', 'oidc', 'local')"
  check_instance_grant_decision           = "decision IN ('granted', 'revoked')"
  check_instance_grant_permission         = "permission IN ('catalogue.manage', 'ops.read', 'instance.circle.create', 'instance.security.manage', 'instance.owner')"
  check_invite_minted_by_kind             = "minted_by_kind IN ('session', 'pat')"
  check_invite_role                       = "role IN ('owner', 'officer', 'member', 'observer')"
  check_membership_kind                   = "kind IN ('human', 'service')"
  check_membership_role                   = "role IN ('owner', 'officer', 'member', 'observer')"
  check_quake_event_source                = "source IN ('log_line', 'manual', 'api', 'import')"
  check_raid_target_category              = "category IN ('open_world', 'zone_boss', 'planar', 'ntov', 'sleeper', 'key_holder')"
  check_raid_target_expansion             = "expansion IN ('classic', 'kunark', 'velious')"
  check_raid_target_state                 = "state IN ('active', 'retired')"
  check_raid_target_timer_server          = "server IN ('blue', 'green', 'red')"
  check_raid_target_timer_window_kind     = "window_kind IN ('fixed', 'variance', 'unknown')"
  check_target_state_cache_change_reason  = "change_reason IN ('new_kill', 'corroboration', 'retraction', 'quake', 'timer_change')"
  check_target_state_cache_confidence     = "confidence IN ('unknown', 'low', 'medium', 'high')"
  check_target_state_cache_contest_reason = "contest_reason IN ('thin_supersede', 'implausible_ordering', 'wide_spread', 'pending_supersede')"
  check_target_state_cache_status         = "status IN ('unknown', 'no_timer', 'pre_window', 'in_window', 'overdue', 'up')"
  check_tod_report_kind                   = "kind IN ('kill', 'retraction')"
  check_tod_report_self_confidence        = "self_confidence IN ('certain', 'probable', 'guess')"
  check_tod_report_source                 = "source IN ('log_line', 'manual', 'api', 'import')"
}
