// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_token.sql

package sqlitegen

import (
	"context"
)

const createAPIToken = `-- name: CreateAPIToken :one

INSERT INTO api_token (
  id, membership_id, token_prefix, token_hash, name, scopes_json, expires_at,
  created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9
)
RETURNING id, membership_id, token_prefix, token_hash, name, scopes_json, last_used_at, expires_at, revoked_at, revoked_by_membership_id, created_at, updated_at
`

type CreateAPITokenParams struct {
	ID           string
	MembershipID string
	TokenPrefix  string
	TokenHash    []byte
	Name         string
	ScopesJson   string
	ExpiresAt    *int64
	CreatedAt    int64
	UpdatedAt    int64
}

// api_token - opaque PATs bound to a membership (ADR-0005). The 8-character prefix is loggable and
// is how a leaked token is found; the hash never leaves the database and the secret is never
// stored at all.
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.ID,
		arg.MembershipID,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.Name,
		arg.ScopesJson,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Name,
		&i.ScopesJson,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, membership_id, token_prefix, token_hash, name, scopes_json, last_used_at, expires_at, revoked_at, revoked_by_membership_id, created_at, updated_at FROM api_token WHERE token_hash = ?1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash []byte) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Name,
		&i.ScopesJson,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPITokensForMembership = `-- name: ListAPITokensForMembership :many
SELECT id, membership_id, token_prefix, token_hash, name, scopes_json, last_used_at, expires_at, revoked_at, revoked_by_membership_id, created_at, updated_at FROM api_token WHERE membership_id = ?1 ORDER BY id DESC
`

func (q *Queries) ListAPITokensForMembership(ctx context.Context, membershipID string) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensForMembership, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.TokenPrefix,
			&i.TokenHash,
			&i.Name,
			&i.ScopesJson,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedByMembershipID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :one
UPDATE api_token
SET revoked_at = ?1,
    revoked_by_membership_id = ?2,
    updated_at = ?3
WHERE id = ?4 AND membership_id = ?5 AND revoked_at IS NULL
RETURNING id, membership_id, token_prefix, token_hash, name, scopes_json, last_used_at, expires_at, revoked_at, revoked_by_membership_id, created_at, updated_at
`

type RevokeAPITokenParams struct {
	RevokedAt             *int64
	RevokedByMembershipID *string
	UpdatedAt             int64
	ID                    string
	MembershipID          string
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, revokeAPIToken,
		arg.RevokedAt,
		arg.RevokedByMembershipID,
		arg.UpdatedAt,
		arg.ID,
		arg.MembershipID,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Name,
		&i.ScopesJson,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_token
SET last_used_at = ?1, updated_at = ?2
WHERE id = ?3
`

type TouchAPITokenParams struct {
	LastUsedAt *int64
	UpdatedAt  int64
	ID         string
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, arg.LastUsedAt, arg.UpdatedAt, arg.ID)
	return err
}
