// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlitegen

import (
	"context"
)

const appendAuditLog = `-- name: AppendAuditLog :one

INSERT INTO audit_log (
  id, circle_id, actor_membership_id, action, entity_type, entity_id, detail_json,
  prev_hash, hash, created_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9, ?10
)
RETURNING id, circle_id, actor_membership_id, "action", entity_type, entity_id, detail_json, prev_hash, hash, created_at
`

type AppendAuditLogParams struct {
	ID                string
	CircleID          string
	ActorMembershipID *string
	Action            string
	EntityType        string
	EntityID          *string
	DetailJson        string
	PrevHash          []byte
	Hash              []byte
	CreatedAt         int64
}

// audit_log - APPEND-ONLY, hash-chained. No UPDATE and no DELETE: a mutable audit log is a
// decoration.
func (q *Queries) AppendAuditLog(ctx context.Context, arg AppendAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, appendAuditLog,
		arg.ID,
		arg.CircleID,
		arg.ActorMembershipID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.DetailJson,
		arg.PrevHash,
		arg.Hash,
		arg.CreatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.ActorMembershipID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.DetailJson,
		&i.PrevHash,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestAuditLogEntry = `-- name: GetLatestAuditLogEntry :one
SELECT id, circle_id, actor_membership_id, "action", entity_type, entity_id, detail_json, prev_hash, hash, created_at FROM audit_log WHERE circle_id = ?1 ORDER BY id DESC LIMIT 1
`

// The tail of the hash chain, so the next entry can name its predecessor.
func (q *Queries) GetLatestAuditLogEntry(ctx context.Context, circleID string) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getLatestAuditLogEntry, circleID)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.ActorMembershipID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.DetailJson,
		&i.PrevHash,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, circle_id, actor_membership_id, "action", entity_type, entity_id, detail_json, prev_hash, hash, created_at FROM audit_log
WHERE circle_id = ?1 AND id < ?2
ORDER BY id DESC
LIMIT ?3
`

type ListAuditLogParams struct {
	CircleID string
	BeforeID string
	RowLimit int64
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLog, arg.CircleID, arg.BeforeID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.ActorMembershipID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.DetailJson,
			&i.PrevHash,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
