// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_flow.sql

package sqlitegen

import (
	"context"
)

const consumeAuthFlow = `-- name: ConsumeAuthFlow :one
UPDATE auth_flow
SET consumed_at = ?1, updated_at = ?2
WHERE state = ?3 AND consumed_at IS NULL
RETURNING id, state, pkce_verifier, provider_id, invite_code_hash, circle_id, expires_at, consumed_at, created_at, updated_at
`

type ConsumeAuthFlowParams struct {
	ConsumedAt *int64
	UpdatedAt  int64
	State      string
}

// `consumed_at IS NULL` in the WHERE is the race-free half; the BEFORE UPDATE trigger is what
// makes a second consumption unrepresentable even if a caller forgets it.
func (q *Queries) ConsumeAuthFlow(ctx context.Context, arg ConsumeAuthFlowParams) (AuthFlow, error) {
	row := q.db.QueryRowContext(ctx, consumeAuthFlow, arg.ConsumedAt, arg.UpdatedAt, arg.State)
	var i AuthFlow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.PkceVerifier,
		&i.ProviderID,
		&i.InviteCodeHash,
		&i.CircleID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuthFlow = `-- name: CreateAuthFlow :one

INSERT INTO auth_flow (
  id, state, pkce_verifier, provider_id, invite_code_hash, circle_id,
  expires_at, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9
)
RETURNING id, state, pkce_verifier, provider_id, invite_code_hash, circle_id, expires_at, consumed_at, created_at, updated_at
`

type CreateAuthFlowParams struct {
	ID             string
	State          string
	PkceVerifier   string
	ProviderID     string
	InviteCodeHash []byte
	CircleID       *string
	ExpiresAt      int64
	CreatedAt      int64
	UpdatedAt      int64
}

// auth_flow - one in-flight browser OAuth authorization. Rows are litter, not history: they are
// swept on expiry, which is why this table has a DELETE and tod_report does not.
func (q *Queries) CreateAuthFlow(ctx context.Context, arg CreateAuthFlowParams) (AuthFlow, error) {
	row := q.db.QueryRowContext(ctx, createAuthFlow,
		arg.ID,
		arg.State,
		arg.PkceVerifier,
		arg.ProviderID,
		arg.InviteCodeHash,
		arg.CircleID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AuthFlow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.PkceVerifier,
		&i.ProviderID,
		&i.InviteCodeHash,
		&i.CircleID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredAuthFlows = `-- name: DeleteExpiredAuthFlows :execrows
DELETE FROM auth_flow WHERE expires_at < ?1
`

func (q *Queries) DeleteExpiredAuthFlows(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredAuthFlows, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAuthFlowByState = `-- name: GetAuthFlowByState :one
SELECT id, state, pkce_verifier, provider_id, invite_code_hash, circle_id, expires_at, consumed_at, created_at, updated_at FROM auth_flow WHERE state = ?1
`

// Looked up by the unguessable server-minted state, never by circle. That is why a missing
// `WHERE circle_id = ?` cannot leak across tenants here (canonical section 9).
func (q *Queries) GetAuthFlowByState(ctx context.Context, state string) (AuthFlow, error) {
	row := q.db.QueryRowContext(ctx, getAuthFlowByState, state)
	var i AuthFlow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.PkceVerifier,
		&i.ProviderID,
		&i.InviteCodeHash,
		&i.CircleID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
