// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: circle_timer_override.sql

package sqlitegen

import (
	"context"
)

const deleteCircleTimerOverride = `-- name: DeleteCircleTimerOverride :execrows
DELETE FROM circle_timer_override
WHERE circle_id = ?1 AND target_id = ?2
`

type DeleteCircleTimerOverrideParams struct {
	CircleID string
	TargetID string
}

func (q *Queries) DeleteCircleTimerOverride(ctx context.Context, arg DeleteCircleTimerOverrideParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCircleTimerOverride, arg.CircleID, arg.TargetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCircleTimerOverride = `-- name: GetCircleTimerOverride :one
SELECT circle_id, target_id, window_kind, window_open_offset_seconds, window_close_offset_seconds, fixed_grace_seconds, cluster_epsilon_seconds, note, created_by_membership_id, created_at, updated_at FROM circle_timer_override
WHERE circle_id = ?1 AND target_id = ?2
`

type GetCircleTimerOverrideParams struct {
	CircleID string
	TargetID string
}

func (q *Queries) GetCircleTimerOverride(ctx context.Context, arg GetCircleTimerOverrideParams) (CircleTimerOverride, error) {
	row := q.db.QueryRowContext(ctx, getCircleTimerOverride, arg.CircleID, arg.TargetID)
	var i CircleTimerOverride
	err := row.Scan(
		&i.CircleID,
		&i.TargetID,
		&i.WindowKind,
		&i.WindowOpenOffsetSeconds,
		&i.WindowCloseOffsetSeconds,
		&i.FixedGraceSeconds,
		&i.ClusterEpsilonSeconds,
		&i.Note,
		&i.CreatedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCircleTimerOverrides = `-- name: ListCircleTimerOverrides :many
SELECT circle_id, target_id, window_kind, window_open_offset_seconds, window_close_offset_seconds, fixed_grace_seconds, cluster_epsilon_seconds, note, created_by_membership_id, created_at, updated_at FROM circle_timer_override WHERE circle_id = ?1 ORDER BY target_id
`

func (q *Queries) ListCircleTimerOverrides(ctx context.Context, circleID string) ([]CircleTimerOverride, error) {
	rows, err := q.db.QueryContext(ctx, listCircleTimerOverrides, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CircleTimerOverride{}
	for rows.Next() {
		var i CircleTimerOverride
		if err := rows.Scan(
			&i.CircleID,
			&i.TargetID,
			&i.WindowKind,
			&i.WindowOpenOffsetSeconds,
			&i.WindowCloseOffsetSeconds,
			&i.FixedGraceSeconds,
			&i.ClusterEpsilonSeconds,
			&i.Note,
			&i.CreatedByMembershipID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putCircleTimerOverride = `-- name: PutCircleTimerOverride :one

INSERT INTO circle_timer_override (
  circle_id, target_id, window_kind, window_open_offset_seconds, window_close_offset_seconds,
  fixed_grace_seconds, cluster_epsilon_seconds, note, created_by_membership_id,
  created_at, updated_at
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5,
  ?6, ?7, ?8,
  ?9, ?10, ?11
)
ON CONFLICT (circle_id, target_id) DO UPDATE SET
  window_kind = excluded.window_kind,
  window_open_offset_seconds = excluded.window_open_offset_seconds,
  window_close_offset_seconds = excluded.window_close_offset_seconds,
  fixed_grace_seconds = excluded.fixed_grace_seconds,
  cluster_epsilon_seconds = excluded.cluster_epsilon_seconds,
  note = excluded.note,
  updated_at = excluded.updated_at
RETURNING circle_id, target_id, window_kind, window_open_offset_seconds, window_close_offset_seconds, fixed_grace_seconds, cluster_epsilon_seconds, note, created_by_membership_id, created_at, updated_at
`

type PutCircleTimerOverrideParams struct {
	CircleID                 string
	TargetID                 string
	WindowKind               string
	WindowOpenOffsetSeconds  *int64
	WindowCloseOffsetSeconds *int64
	FixedGraceSeconds        int64
	ClusterEpsilonSeconds    *int64
	Note                     string
	CreatedByMembershipID    string
	CreatedAt                int64
	UpdatedAt                int64
}

// circle_timer_override - this circle disagrees with the catalogue. Resolution order is circle
// override -> catalogue timer -> unknown.
func (q *Queries) PutCircleTimerOverride(ctx context.Context, arg PutCircleTimerOverrideParams) (CircleTimerOverride, error) {
	row := q.db.QueryRowContext(ctx, putCircleTimerOverride,
		arg.CircleID,
		arg.TargetID,
		arg.WindowKind,
		arg.WindowOpenOffsetSeconds,
		arg.WindowCloseOffsetSeconds,
		arg.FixedGraceSeconds,
		arg.ClusterEpsilonSeconds,
		arg.Note,
		arg.CreatedByMembershipID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CircleTimerOverride
	err := row.Scan(
		&i.CircleID,
		&i.TargetID,
		&i.WindowKind,
		&i.WindowOpenOffsetSeconds,
		&i.WindowCloseOffsetSeconds,
		&i.FixedGraceSeconds,
		&i.ClusterEpsilonSeconds,
		&i.Note,
		&i.CreatedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
