// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: circle.sql

package sqlitegen

import (
	"context"
)

const createCircle = `-- name: CreateCircle :one

INSERT INTO circle (
  id, name, name_norm, description, server, timezone,
  min_reporters_to_supersede, revoke_invalidates_invites, state, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10, ?11
)
RETURNING id, name, name_norm, description, server, timezone, min_reporters_to_supersede, revoke_invalidates_invites, state, deleted_at, created_at, updated_at
`

type CreateCircleParams struct {
	CircleID                 string
	Name                     string
	NameNorm                 string
	Description              string
	Server                   string
	Timezone                 string
	MinReportersToSupersede  int64
	RevokeInvalidatesInvites int64
	State                    string
	CreatedAt                int64
	UpdatedAt                int64
}

// circle - the tenant root. Its own `id` IS the tenant key, so every query names it as
// sqlc.arg(circle_id): the parameter a caller passes is a circle id, and spelling it that way
// keeps the generated Go honest about what it is.
//
// `server` is absent from UpdateCircle on purpose. It is immutable after creation - a BEFORE
// UPDATE trigger enforces it and the edge answers 422 field_immutable - and a query that offered
// to set it would be a second opinion about that.
func (q *Queries) CreateCircle(ctx context.Context, arg CreateCircleParams) (Circle, error) {
	row := q.db.QueryRowContext(ctx, createCircle,
		arg.CircleID,
		arg.Name,
		arg.NameNorm,
		arg.Description,
		arg.Server,
		arg.Timezone,
		arg.MinReportersToSupersede,
		arg.RevokeInvalidatesInvites,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNorm,
		&i.Description,
		&i.Server,
		&i.Timezone,
		&i.MinReportersToSupersede,
		&i.RevokeInvalidatesInvites,
		&i.State,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCircle = `-- name: GetCircle :one
SELECT id, name, name_norm, description, server, timezone, min_reporters_to_supersede, revoke_invalidates_invites, state, deleted_at, created_at, updated_at FROM circle WHERE id = ?1 AND deleted_at IS NULL
`

// A tombstoned circle does not exist to a reader. deleteCircle cannot remove the row -- the
// append-only tables referencing it forbid that -- so "deleted" is a predicate every read carries
// rather than an absence the database enforces.
func (q *Queries) GetCircle(ctx context.Context, circleID string) (Circle, error) {
	row := q.db.QueryRowContext(ctx, getCircle, circleID)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNorm,
		&i.Description,
		&i.Server,
		&i.Timezone,
		&i.MinReportersToSupersede,
		&i.RevokeInvalidatesInvites,
		&i.State,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCirclesForIdentity = `-- name: ListCirclesForIdentity :many
SELECT c.id, c.name, c.name_norm, c.description, c.server, c.timezone, c.min_reporters_to_supersede, c.revoke_invalidates_invites, c.state, c.deleted_at, c.created_at, c.updated_at FROM circle c
JOIN membership m ON m.circle_id = c.id
WHERE m.identity_id = ?1 AND m.revoked_at IS NULL AND c.deleted_at IS NULL
ORDER BY c.id
`

// tenancy: keyed on a VERIFIED identity's own memberships, never on a caller-supplied circle id.
// This is the lookup the OAuth callback makes at step 4 and the one listCircles serves; both take
// the identity from something the caller proved, so there is no id here to enumerate.
func (q *Queries) ListCirclesForIdentity(ctx context.Context, identityID *string) ([]Circle, error) {
	rows, err := q.db.QueryContext(ctx, listCirclesForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Circle{}
	for rows.Next() {
		var i Circle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNorm,
			&i.Description,
			&i.Server,
			&i.Timezone,
			&i.MinReportersToSupersede,
			&i.RevokeInvalidatesInvites,
			&i.State,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveCircles = `-- name: ListLiveCircles :many
SELECT id, name, name_norm, description, server, timezone, min_reporters_to_supersede, revoke_invalidates_invites, state, deleted_at, created_at, updated_at FROM circle WHERE deleted_at IS NULL ORDER BY id
`

// tenancy: the projection's rebuild and its nightly verify job sweep every circle. They have no
// caller and no tenant to be filtered by -- a maintenance job that could only see one circle would
// leave every other circle's cache unverified, which is the whole thing the job exists to stop.
func (q *Queries) ListLiveCircles(ctx context.Context) ([]Circle, error) {
	rows, err := q.db.QueryContext(ctx, listLiveCircles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Circle{}
	for rows.Next() {
		var i Circle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNorm,
			&i.Description,
			&i.Server,
			&i.Timezone,
			&i.MinReportersToSupersede,
			&i.RevokeInvalidatesInvites,
			&i.State,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveCirclesOnServer = `-- name: ListLiveCirclesOnServer :many
SELECT id, name, name_norm, description, server, timezone, min_reporters_to_supersede, revoke_invalidates_invites, state, deleted_at, created_at, updated_at FROM circle
WHERE deleted_at IS NULL AND server = ?1
ORDER BY id
`

// tenancy: a catalogue timer is instance-wide and PER SERVER, so writing one moves the window for
// every circle pinned to that server. There is no single tenant to filter by -- the whole point of
// this query is the fan-out, and a version that took a circle_id could not express it.
func (q *Queries) ListLiveCirclesOnServer(ctx context.Context, server string) ([]Circle, error) {
	rows, err := q.db.QueryContext(ctx, listLiveCirclesOnServer, server)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Circle{}
	for rows.Next() {
		var i Circle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNorm,
			&i.Description,
			&i.Server,
			&i.Timezone,
			&i.MinReportersToSupersede,
			&i.RevokeInvalidatesInvites,
			&i.State,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCircle = `-- name: SoftDeleteCircle :one
UPDATE circle
SET deleted_at = ?1, updated_at = ?2
WHERE id = ?3 AND deleted_at IS NULL
RETURNING id, name, name_norm, description, server, timezone, min_reporters_to_supersede, revoke_invalidates_invites, state, deleted_at, created_at, updated_at
`

type SoftDeleteCircleParams struct {
	DeletedAt *int64
	UpdatedAt int64
	CircleID  string
}

// The tombstone deleteCircle writes. `deleted_at IS NULL` makes a second delete return no row
// rather than moving the timestamp, so the moment a circle stopped existing is the first one.
func (q *Queries) SoftDeleteCircle(ctx context.Context, arg SoftDeleteCircleParams) (Circle, error) {
	row := q.db.QueryRowContext(ctx, softDeleteCircle, arg.DeletedAt, arg.UpdatedAt, arg.CircleID)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNorm,
		&i.Description,
		&i.Server,
		&i.Timezone,
		&i.MinReportersToSupersede,
		&i.RevokeInvalidatesInvites,
		&i.State,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCircle = `-- name: UpdateCircle :one
UPDATE circle
SET name = ?1, name_norm = ?2, description = ?3,
    timezone = ?4,
    min_reporters_to_supersede = ?5,
    revoke_invalidates_invites = ?6,
    state = ?7, updated_at = ?8
WHERE id = ?9
RETURNING id, name, name_norm, description, server, timezone, min_reporters_to_supersede, revoke_invalidates_invites, state, deleted_at, created_at, updated_at
`

type UpdateCircleParams struct {
	Name                     string
	NameNorm                 string
	Description              string
	Timezone                 string
	MinReportersToSupersede  int64
	RevokeInvalidatesInvites int64
	State                    string
	UpdatedAt                int64
	CircleID                 string
}

func (q *Queries) UpdateCircle(ctx context.Context, arg UpdateCircleParams) (Circle, error) {
	row := q.db.QueryRowContext(ctx, updateCircle,
		arg.Name,
		arg.NameNorm,
		arg.Description,
		arg.Timezone,
		arg.MinReportersToSupersede,
		arg.RevokeInvalidatesInvites,
		arg.State,
		arg.UpdatedAt,
		arg.CircleID,
	)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNorm,
		&i.Description,
		&i.Server,
		&i.Timezone,
		&i.MinReportersToSupersede,
		&i.RevokeInvalidatesInvites,
		&i.State,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
