// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: circle_discord_channel.sql

package sqlitegen

import (
	"context"
)

const bindCircleDiscordChannel = `-- name: BindCircleDiscordChannel :one

INSERT INTO circle_discord_channel (
  discord_channel_id, circle_id, discord_guild_id, allow_visible, created_by_membership_id,
  created_at, updated_at
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5, ?6,
  ?7
)
ON CONFLICT (discord_channel_id) DO UPDATE SET
  circle_id = excluded.circle_id,
  discord_guild_id = excluded.discord_guild_id,
  allow_visible = excluded.allow_visible,
  created_by_membership_id = excluded.created_by_membership_id,
  updated_at = excluded.updated_at
RETURNING discord_channel_id, circle_id, discord_guild_id, allow_visible, created_by_membership_id, created_at, updated_at
`

type BindCircleDiscordChannelParams struct {
	DiscordChannelID      string
	CircleID              string
	DiscordGuildID        string
	AllowVisible          int64
	CreatedByMembershipID string
	CreatedAt             int64
	UpdatedAt             int64
}

// circle_discord_channel - a Discord channel bound to ONE circle. ADR-0017.
//
// The binding is BOTH halves of the answer: it disambiguates a guild that names several circles,
// and it is the stored, per-channel opt-in that makes a visible reply something an officer decided
// rather than something this server guessed. Discord has no channel-membership API, so nobody --
// this server included -- can enumerate who reads a visible message.
// Create or replace the binding for one channel. The conflict target is the CHANNEL, because the
// primary key is the channel alone: rebinding a channel that belonged to a tombstoned circle is a
// replace, and rebinding one that belongs to a live circle is refused in Go before this runs --
// silently redirecting a channel would move a disclosure decision nobody made.
func (q *Queries) BindCircleDiscordChannel(ctx context.Context, arg BindCircleDiscordChannelParams) (CircleDiscordChannel, error) {
	row := q.db.QueryRowContext(ctx, bindCircleDiscordChannel,
		arg.DiscordChannelID,
		arg.CircleID,
		arg.DiscordGuildID,
		arg.AllowVisible,
		arg.CreatedByMembershipID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CircleDiscordChannel
	err := row.Scan(
		&i.DiscordChannelID,
		&i.CircleID,
		&i.DiscordGuildID,
		&i.AllowVisible,
		&i.CreatedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCircleDiscordChannel = `-- name: GetCircleDiscordChannel :one
SELECT cdc.discord_channel_id, cdc.circle_id, cdc.discord_guild_id, cdc.allow_visible, cdc.created_by_membership_id, cdc.created_at, cdc.updated_at, c.deleted_at AS circle_deleted_at
FROM circle_discord_channel cdc
JOIN circle c ON c.id = cdc.circle_id
WHERE cdc.discord_channel_id = ?1
`

type GetCircleDiscordChannelRow struct {
	DiscordChannelID      string
	CircleID              string
	DiscordGuildID        string
	AllowVisible          int64
	CreatedByMembershipID string
	CreatedAt             int64
	UpdatedAt             int64
	CircleDeletedAt       *int64
}

// tenancy: this is the RESOLVE, and it is the one query here that cannot name a circle_id -- it is
// what PRODUCES one. An interaction arrives carrying a channel and a guild and no trustworthy
// circle: accepting a circle id from that payload is the cross-circle-ids-in-bodies class #29
// closed. So the channel is the key, and every circle-scoped read downstream is filtered by the
// circle_id this row returns.
//
// The guild is compared by the CALLER rather than here, so a mismatch is distinguishable from an
// unbound channel. Both refuse, but only one of them means an officer should go and bind it.
//
// It carries the circle's deleted_at because a tombstoned circle keeps its bindings -- nothing
// deletes them, exactly as nothing deletes circle_provider's rows -- so the resolve has to see
// that the circle is gone rather than answer for it.
func (q *Queries) GetCircleDiscordChannel(ctx context.Context, discordChannelID string) (GetCircleDiscordChannelRow, error) {
	row := q.db.QueryRowContext(ctx, getCircleDiscordChannel, discordChannelID)
	var i GetCircleDiscordChannelRow
	err := row.Scan(
		&i.DiscordChannelID,
		&i.CircleID,
		&i.DiscordGuildID,
		&i.AllowVisible,
		&i.CreatedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CircleDeletedAt,
	)
	return i, err
}

const getCircleDiscordChannelInCircle = `-- name: GetCircleDiscordChannelInCircle :one
SELECT discord_channel_id, circle_id, discord_guild_id, allow_visible, created_by_membership_id, created_at, updated_at FROM circle_discord_channel
WHERE circle_id = ?1 AND discord_channel_id = ?2
`

type GetCircleDiscordChannelInCircleParams struct {
	CircleID         string
	DiscordChannelID string
}

func (q *Queries) GetCircleDiscordChannelInCircle(ctx context.Context, arg GetCircleDiscordChannelInCircleParams) (CircleDiscordChannel, error) {
	row := q.db.QueryRowContext(ctx, getCircleDiscordChannelInCircle, arg.CircleID, arg.DiscordChannelID)
	var i CircleDiscordChannel
	err := row.Scan(
		&i.DiscordChannelID,
		&i.CircleID,
		&i.DiscordGuildID,
		&i.AllowVisible,
		&i.CreatedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCircleDiscordChannels = `-- name: ListCircleDiscordChannels :many
SELECT discord_channel_id, circle_id, discord_guild_id, allow_visible, created_by_membership_id, created_at, updated_at FROM circle_discord_channel
WHERE circle_id = ?1
ORDER BY discord_channel_id
`

// "Which channels does this circle disclose into?" is the question an officer asks before a raid
// and an audit asks afterwards. ix_circle_discord_channel_circle_id is what stops it being a scan.
func (q *Queries) ListCircleDiscordChannels(ctx context.Context, circleID string) ([]CircleDiscordChannel, error) {
	rows, err := q.db.QueryContext(ctx, listCircleDiscordChannels, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CircleDiscordChannel{}
	for rows.Next() {
		var i CircleDiscordChannel
		if err := rows.Scan(
			&i.DiscordChannelID,
			&i.CircleID,
			&i.DiscordGuildID,
			&i.AllowVisible,
			&i.CreatedByMembershipID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbindCircleDiscordChannel = `-- name: UnbindCircleDiscordChannel :execrows
DELETE FROM circle_discord_channel
WHERE circle_id = ?1 AND discord_channel_id = ?2
`

type UnbindCircleDiscordChannelParams struct {
	CircleID         string
	DiscordChannelID string
}

// Unbinding stops the NEXT message. It unsays nothing: whatever was posted while the binding was
// live is Discord's now, and Discord keeps it.
func (q *Queries) UnbindCircleDiscordChannel(ctx context.Context, arg UnbindCircleDiscordChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unbindCircleDiscordChannel, arg.CircleID, arg.DiscordChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
