// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: circle_provider.sql

package sqlitegen

import (
	"context"
)

const deleteCircleProvider = `-- name: DeleteCircleProvider :execrows
DELETE FROM circle_provider
WHERE circle_id = ?1 AND provider_id = ?2
`

type DeleteCircleProviderParams struct {
	CircleID   string
	ProviderID string
}

// Stops NEW joins via that provider. It does not revoke existing memberships: mass-revoke on
// removal is a footgun that eventually deletes a guild's whole roster with one click.
func (q *Queries) DeleteCircleProvider(ctx context.Context, arg DeleteCircleProviderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCircleProvider, arg.CircleID, arg.ProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCircleProvider = `-- name: GetCircleProvider :one
SELECT circle_id, provider_id, discord_guild_id, discord_required_role_ids_json, created_at, updated_at FROM circle_provider
WHERE circle_id = ?1 AND provider_id = ?2
`

type GetCircleProviderParams struct {
	CircleID   string
	ProviderID string
}

func (q *Queries) GetCircleProvider(ctx context.Context, arg GetCircleProviderParams) (CircleProvider, error) {
	row := q.db.QueryRowContext(ctx, getCircleProvider, arg.CircleID, arg.ProviderID)
	var i CircleProvider
	err := row.Scan(
		&i.CircleID,
		&i.ProviderID,
		&i.DiscordGuildID,
		&i.DiscordRequiredRoleIdsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCircleProviders = `-- name: ListCircleProviders :many
SELECT circle_id, provider_id, discord_guild_id, discord_required_role_ids_json, created_at, updated_at FROM circle_provider WHERE circle_id = ?1 ORDER BY provider_id
`

func (q *Queries) ListCircleProviders(ctx context.Context, circleID string) ([]CircleProvider, error) {
	rows, err := q.db.QueryContext(ctx, listCircleProviders, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CircleProvider{}
	for rows.Next() {
		var i CircleProvider
		if err := rows.Scan(
			&i.CircleID,
			&i.ProviderID,
			&i.DiscordGuildID,
			&i.DiscordRequiredRoleIdsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putCircleProvider = `-- name: PutCircleProvider :one

INSERT INTO circle_provider (
  circle_id, provider_id, discord_guild_id, discord_required_role_ids_json, created_at, updated_at
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5, ?6
)
ON CONFLICT (circle_id, provider_id) DO UPDATE SET
  discord_guild_id = excluded.discord_guild_id,
  discord_required_role_ids_json = excluded.discord_required_role_ids_json,
  updated_at = excluded.updated_at
RETURNING circle_id, provider_id, discord_guild_id, discord_required_role_ids_json, created_at, updated_at
`

type PutCircleProviderParams struct {
	CircleID                   string
	ProviderID                 string
	DiscordGuildID             *string
	DiscordRequiredRoleIdsJson string
	CreatedAt                  int64
	UpdatedAt                  int64
}

// circle_provider - which instance providers this circle accepts, and the Discord guild gate.
// An empty discord_required_role_ids_json means "anyone in the guild"; a NULL discord_guild_id
// means the circle does not gate on a guild at all.
func (q *Queries) PutCircleProvider(ctx context.Context, arg PutCircleProviderParams) (CircleProvider, error) {
	row := q.db.QueryRowContext(ctx, putCircleProvider,
		arg.CircleID,
		arg.ProviderID,
		arg.DiscordGuildID,
		arg.DiscordRequiredRoleIdsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CircleProvider
	err := row.Scan(
		&i.CircleID,
		&i.ProviderID,
		&i.DiscordGuildID,
		&i.DiscordRequiredRoleIdsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
