// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: circle.sql

package sqlitegen

import (
	"context"
)

const createCircle = `-- name: CreateCircle :one

INSERT INTO circle (
  id, name, name_norm, description, server, timezone,
  min_reporters_to_supersede, revoke_invalidates_invites, state, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10, ?11
)
RETURNING id, name, name_norm, description, server, timezone, min_reporters_to_supersede, revoke_invalidates_invites, state, created_at, updated_at
`

type CreateCircleParams struct {
	CircleID                 string
	Name                     string
	NameNorm                 string
	Description              string
	Server                   string
	Timezone                 string
	MinReportersToSupersede  int64
	RevokeInvalidatesInvites int64
	State                    string
	CreatedAt                int64
	UpdatedAt                int64
}

// circle - the tenant root. Its own `id` IS the tenant key, so every query names it as
// sqlc.arg(circle_id): the parameter a caller passes is a circle id, and spelling it that way
// keeps the generated Go honest about what it is.
//
// `server` is absent from UpdateCircle on purpose. It is immutable after creation - a BEFORE
// UPDATE trigger enforces it and the edge answers 422 field_immutable - and a query that offered
// to set it would be a second opinion about that.
func (q *Queries) CreateCircle(ctx context.Context, arg CreateCircleParams) (Circle, error) {
	row := q.db.QueryRowContext(ctx, createCircle,
		arg.CircleID,
		arg.Name,
		arg.NameNorm,
		arg.Description,
		arg.Server,
		arg.Timezone,
		arg.MinReportersToSupersede,
		arg.RevokeInvalidatesInvites,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNorm,
		&i.Description,
		&i.Server,
		&i.Timezone,
		&i.MinReportersToSupersede,
		&i.RevokeInvalidatesInvites,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCircle = `-- name: GetCircle :one
SELECT id, name, name_norm, description, server, timezone, min_reporters_to_supersede, revoke_invalidates_invites, state, created_at, updated_at FROM circle WHERE id = ?1
`

func (q *Queries) GetCircle(ctx context.Context, circleID string) (Circle, error) {
	row := q.db.QueryRowContext(ctx, getCircle, circleID)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNorm,
		&i.Description,
		&i.Server,
		&i.Timezone,
		&i.MinReportersToSupersede,
		&i.RevokeInvalidatesInvites,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCirclesForIdentity = `-- name: ListCirclesForIdentity :many
SELECT c.id, c.name, c.name_norm, c.description, c.server, c.timezone, c.min_reporters_to_supersede, c.revoke_invalidates_invites, c.state, c.created_at, c.updated_at FROM circle c
JOIN membership m ON m.circle_id = c.id
WHERE m.identity_id = ?1 AND m.revoked_at IS NULL
ORDER BY c.id
`

// tenancy: keyed on a VERIFIED identity's own memberships, never on a caller-supplied circle id.
// This is the lookup the OAuth callback makes at step 4 and the one listCircles serves; both take
// the identity from something the caller proved, so there is no id here to enumerate.
func (q *Queries) ListCirclesForIdentity(ctx context.Context, identityID *string) ([]Circle, error) {
	rows, err := q.db.QueryContext(ctx, listCirclesForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Circle{}
	for rows.Next() {
		var i Circle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNorm,
			&i.Description,
			&i.Server,
			&i.Timezone,
			&i.MinReportersToSupersede,
			&i.RevokeInvalidatesInvites,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCircle = `-- name: UpdateCircle :one
UPDATE circle
SET name = ?1, name_norm = ?2, description = ?3,
    timezone = ?4,
    min_reporters_to_supersede = ?5,
    revoke_invalidates_invites = ?6,
    state = ?7, updated_at = ?8
WHERE id = ?9
RETURNING id, name, name_norm, description, server, timezone, min_reporters_to_supersede, revoke_invalidates_invites, state, created_at, updated_at
`

type UpdateCircleParams struct {
	Name                     string
	NameNorm                 string
	Description              string
	Timezone                 string
	MinReportersToSupersede  int64
	RevokeInvalidatesInvites int64
	State                    string
	UpdatedAt                int64
	CircleID                 string
}

func (q *Queries) UpdateCircle(ctx context.Context, arg UpdateCircleParams) (Circle, error) {
	row := q.db.QueryRowContext(ctx, updateCircle,
		arg.Name,
		arg.NameNorm,
		arg.Description,
		arg.Timezone,
		arg.MinReportersToSupersede,
		arg.RevokeInvalidatesInvites,
		arg.State,
		arg.UpdatedAt,
		arg.CircleID,
	)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNorm,
		&i.Description,
		&i.Server,
		&i.Timezone,
		&i.MinReportersToSupersede,
		&i.RevokeInvalidatesInvites,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
