// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credential_ticket.sql

package sqlitegen

import (
	"context"
)

const consumeCredentialTicket = `-- name: ConsumeCredentialTicket :one
UPDATE credential_ticket
SET consumed_at = ?1, updated_at = ?2
WHERE ticket_hash = ?3 AND consumed_at IS NULL
RETURNING id, ticket_hash, provider_id, subject, display_name, guild_roles_json, expires_at, consumed_at, created_at, updated_at
`

type ConsumeCredentialTicketParams struct {
	ConsumedAt *int64
	UpdatedAt  int64
	TicketHash []byte
}

// A second redemption is 401 auth_ticket_invalid. This returns no row when the ticket is already
// consumed, and the BEFORE UPDATE trigger aborts a write that tried anyway.
func (q *Queries) ConsumeCredentialTicket(ctx context.Context, arg ConsumeCredentialTicketParams) (CredentialTicket, error) {
	row := q.db.QueryRowContext(ctx, consumeCredentialTicket, arg.ConsumedAt, arg.UpdatedAt, arg.TicketHash)
	var i CredentialTicket
	err := row.Scan(
		&i.ID,
		&i.TicketHash,
		&i.ProviderID,
		&i.Subject,
		&i.DisplayName,
		&i.GuildRolesJson,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCredentialTicket = `-- name: CreateCredentialTicket :one

INSERT INTO credential_ticket (
  id, ticket_hash, provider_id, subject, display_name, guild_roles_json,
  expires_at, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9
)
RETURNING id, ticket_hash, provider_id, subject, display_name, guild_roles_json, expires_at, consumed_at, created_at, updated_at
`

type CreateCredentialTicketParams struct {
	ID             string
	TicketHash     []byte
	ProviderID     string
	Subject        string
	DisplayName    string
	GuildRolesJson string
	ExpiresAt      int64
	CreatedAt      int64
	UpdatedAt      int64
}

// credential_ticket - a verified subject for 120 seconds, single-use, redeemable at either /join
// or /sessions.
func (q *Queries) CreateCredentialTicket(ctx context.Context, arg CreateCredentialTicketParams) (CredentialTicket, error) {
	row := q.db.QueryRowContext(ctx, createCredentialTicket,
		arg.ID,
		arg.TicketHash,
		arg.ProviderID,
		arg.Subject,
		arg.DisplayName,
		arg.GuildRolesJson,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CredentialTicket
	err := row.Scan(
		&i.ID,
		&i.TicketHash,
		&i.ProviderID,
		&i.Subject,
		&i.DisplayName,
		&i.GuildRolesJson,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredCredentialTickets = `-- name: DeleteExpiredCredentialTickets :execrows
DELETE FROM credential_ticket WHERE expires_at < ?1
`

func (q *Queries) DeleteExpiredCredentialTickets(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredCredentialTickets, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCredentialTicketByHash = `-- name: GetCredentialTicketByHash :one
SELECT id, ticket_hash, provider_id, subject, display_name, guild_roles_json, expires_at, consumed_at, created_at, updated_at FROM credential_ticket WHERE ticket_hash = ?1
`

// By hash, never by circle: which circle the ticket lands in is settled at redemption.
func (q *Queries) GetCredentialTicketByHash(ctx context.Context, ticketHash []byte) (CredentialTicket, error) {
	row := q.db.QueryRowContext(ctx, getCredentialTicketByHash, ticketHash)
	var i CredentialTicket
	err := row.Scan(
		&i.ID,
		&i.TicketHash,
		&i.ProviderID,
		&i.Subject,
		&i.DisplayName,
		&i.GuildRolesJson,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
