// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_outbox.sql

package sqlitegen

import (
	"context"
)

const appendEvent = `-- name: AppendEvent :one

INSERT INTO event_outbox (id, circle_id, kind, payload_json, created_at)
VALUES (
  ?1, ?2, ?3, ?4, ?5
)
RETURNING event_seq, id, circle_id, kind, payload_json, created_at
`

type AppendEventParams struct {
	ID          string
	CircleID    *string
	Kind        string
	PayloadJson string
	CreatedAt   int64
}

// event_outbox - append-only, and the home of the one global sequence (canonical section 4). No UPDATE
// and no DELETE: a delivered event that could be edited is a replay a client cannot trust.
//
// `circle_id` is nullable because an instance-level event belongs to no circle, which is why this
// table is instance-scoped. Every per-circle read still names it.
func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (EventOutbox, error) {
	row := q.db.QueryRowContext(ctx, appendEvent,
		arg.ID,
		arg.CircleID,
		arg.Kind,
		arg.PayloadJson,
		arg.CreatedAt,
	)
	var i EventOutbox
	err := row.Scan(
		&i.EventSeq,
		&i.ID,
		&i.CircleID,
		&i.Kind,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestEventSeq = `-- name: GetLatestEventSeq :one
SELECT COALESCE(MAX(event_seq), 0) AS event_seq FROM event_outbox
`

func (q *Queries) GetLatestEventSeq(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestEventSeq)
	var event_seq interface{}
	err := row.Scan(&event_seq)
	return event_seq, err
}

const listCircleEventsSince = `-- name: ListCircleEventsSince :many
SELECT event_seq, id, circle_id, kind, payload_json, created_at FROM event_outbox
WHERE circle_id = ?1 AND event_seq > ?2
ORDER BY event_seq
LIMIT ?3
`

type ListCircleEventsSinceParams struct {
	CircleID *string
	SinceSeq int64
	RowLimit int64
}

func (q *Queries) ListCircleEventsSince(ctx context.Context, arg ListCircleEventsSinceParams) ([]EventOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listCircleEventsSince, arg.CircleID, arg.SinceSeq, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventOutbox{}
	for rows.Next() {
		var i EventOutbox
		if err := rows.Scan(
			&i.EventSeq,
			&i.ID,
			&i.CircleID,
			&i.Kind,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
