// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_record.sql

package sqlitegen

import (
	"context"
)

const completeIdempotencyRecord = `-- name: CompleteIdempotencyRecord :one
UPDATE idempotency_record
SET response_status = ?1,
    response_body = ?2,
    completed_at = ?3,
    updated_at = ?4
WHERE id = ?5 AND completed_at IS NULL
RETURNING id, principal_membership_id, "key", request_hash, response_status, response_body, completed_at, expires_at, created_at, updated_at
`

type CompleteIdempotencyRecordParams struct {
	ResponseStatus *int64
	ResponseBody   *string
	CompletedAt    *int64
	UpdatedAt      int64
	ID             string
}

func (q *Queries) CompleteIdempotencyRecord(ctx context.Context, arg CompleteIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRowContext(ctx, completeIdempotencyRecord,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.PrincipalMembershipID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIdempotencyRecord = `-- name: CreateIdempotencyRecord :one

INSERT INTO idempotency_record (
  id, principal_membership_id, key, request_hash, expires_at, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7
)
RETURNING id, principal_membership_id, "key", request_hash, response_status, response_body, completed_at, expires_at, created_at, updated_at
`

type CreateIdempotencyRecordParams struct {
	ID                    string
	PrincipalMembershipID string
	Key                   string
	RequestHash           []byte
	ExpiresAt             int64
	CreatedAt             int64
	UpdatedAt             int64
}

// idempotency_record - (principal, key) -> the request that was made and the response returned.
// The principal is the MEMBERSHIP, never the token, so a rotation mid-retry still replays.
func (q *Queries) CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRowContext(ctx, createIdempotencyRecord,
		arg.ID,
		arg.PrincipalMembershipID,
		arg.Key,
		arg.RequestHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.PrincipalMembershipID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredIdempotencyRecords = `-- name: DeleteExpiredIdempotencyRecords :execrows
DELETE FROM idempotency_record WHERE expires_at < ?1
`

func (q *Queries) DeleteExpiredIdempotencyRecords(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredIdempotencyRecords, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT id, principal_membership_id, "key", request_hash, response_status, response_body, completed_at, expires_at, created_at, updated_at FROM idempotency_record
WHERE principal_membership_id = ?1 AND key = ?2
`

type GetIdempotencyRecordParams struct {
	PrincipalMembershipID string
	Key                   string
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyRecord, arg.PrincipalMembershipID, arg.Key)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.PrincipalMembershipID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
