// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_link.sql

package sqlitegen

import (
	"context"
)

const createIdentityLink = `-- name: CreateIdentityLink :one

INSERT INTO identity_link (
  id, primary_identity_id, linked_identity_id, method, linked_by_membership_id, linked_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6
)
RETURNING id, primary_identity_id, linked_identity_id, method, linked_by_membership_id, linked_at
`

type CreateIdentityLinkParams struct {
	ID                   string
	PrimaryIdentityID    string
	LinkedIdentityID     string
	Method               string
	LinkedByMembershipID string
	LinkedAt             int64
}

// identity_link - append-only. No UPDATE and no DELETE, ever: revoking a membership revokes it
// across the whole link set, and a link that could be quietly removed would reopen the second door
// it exists to close.
func (q *Queries) CreateIdentityLink(ctx context.Context, arg CreateIdentityLinkParams) (IdentityLink, error) {
	row := q.db.QueryRowContext(ctx, createIdentityLink,
		arg.ID,
		arg.PrimaryIdentityID,
		arg.LinkedIdentityID,
		arg.Method,
		arg.LinkedByMembershipID,
		arg.LinkedAt,
	)
	var i IdentityLink
	err := row.Scan(
		&i.ID,
		&i.PrimaryIdentityID,
		&i.LinkedIdentityID,
		&i.Method,
		&i.LinkedByMembershipID,
		&i.LinkedAt,
	)
	return i, err
}

const listIdentityLinksFor = `-- name: ListIdentityLinksFor :many
SELECT id, primary_identity_id, linked_identity_id, method, linked_by_membership_id, linked_at FROM identity_link
WHERE primary_identity_id = ?1 OR linked_identity_id = ?1
ORDER BY id
`

func (q *Queries) ListIdentityLinksFor(ctx context.Context, identityID string) ([]IdentityLink, error) {
	rows, err := q.db.QueryContext(ctx, listIdentityLinksFor, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityLink{}
	for rows.Next() {
		var i IdentityLink
		if err := rows.Scan(
			&i.ID,
			&i.PrimaryIdentityID,
			&i.LinkedIdentityID,
			&i.Method,
			&i.LinkedByMembershipID,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
