// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlitegen

import (
	"context"
)

const blockIdentity = `-- name: BlockIdentity :one
UPDATE identity
SET blocked_at = ?1,
    blocked_by_membership_id = ?2,
    block_reason = ?3,
    updated_at = ?4
WHERE id = ?5
RETURNING id, provider_id, subject, display_name, blocked_at, blocked_by_membership_id, block_reason, created_at, updated_at
`

type BlockIdentityParams struct {
	BlockedAt             *int64
	BlockedByMembershipID *string
	BlockReason           *string
	UpdatedAt             int64
	ID                    string
}

// The instance operator's decision about their whole instance, refused at join AND at ticket
// redemption, so a second circle is not a second door.
func (q *Queries) BlockIdentity(ctx context.Context, arg BlockIdentityParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, blockIdentity,
		arg.BlockedAt,
		arg.BlockedByMembershipID,
		arg.BlockReason,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Subject,
		&i.DisplayName,
		&i.BlockedAt,
		&i.BlockedByMembershipID,
		&i.BlockReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIdentity = `-- name: CreateIdentity :one

INSERT INTO identity (id, provider_id, subject, display_name, created_at, updated_at)
VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6
)
RETURNING id, provider_id, subject, display_name, blocked_at, blocked_by_membership_id, block_reason, created_at, updated_at
`

type CreateIdentityParams struct {
	ID          string
	ProviderID  string
	Subject     string
	DisplayName string
	CreatedAt   int64
	UpdatedAt   int64
}

// identity - a (provider, subject) pair, instance-wide.
func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, createIdentity,
		arg.ID,
		arg.ProviderID,
		arg.Subject,
		arg.DisplayName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Subject,
		&i.DisplayName,
		&i.BlockedAt,
		&i.BlockedByMembershipID,
		&i.BlockReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentity = `-- name: GetIdentity :one
SELECT id, provider_id, subject, display_name, blocked_at, blocked_by_membership_id, block_reason, created_at, updated_at FROM identity WHERE id = ?1
`

func (q *Queries) GetIdentity(ctx context.Context, id string) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentity, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Subject,
		&i.DisplayName,
		&i.BlockedAt,
		&i.BlockedByMembershipID,
		&i.BlockReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByProviderSubject = `-- name: GetIdentityByProviderSubject :one
SELECT id, provider_id, subject, display_name, blocked_at, blocked_by_membership_id, block_reason, created_at, updated_at FROM identity
WHERE provider_id = ?1 AND subject = ?2
`

type GetIdentityByProviderSubjectParams struct {
	ProviderID string
	Subject    string
}

func (q *Queries) GetIdentityByProviderSubject(ctx context.Context, arg GetIdentityByProviderSubjectParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByProviderSubject, arg.ProviderID, arg.Subject)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Subject,
		&i.DisplayName,
		&i.BlockedAt,
		&i.BlockedByMembershipID,
		&i.BlockReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentities = `-- name: ListIdentities :many
SELECT i.id, i.provider_id, i.subject, i.display_name, i.blocked_at, i.blocked_by_membership_id, i.block_reason, i.created_at, i.updated_at, p.key AS provider_key
FROM identity i
JOIN identity_provider p ON p.id = i.provider_id
ORDER BY p.key, i.subject
`

type ListIdentitiesRow struct {
	ID                    string
	ProviderID            string
	Subject               string
	DisplayName           string
	BlockedAt             *int64
	BlockedByMembershipID *string
	BlockReason           *string
	CreatedAt             int64
	UpdatedAt             int64
	ProviderKey           string
}

// The console listing: which people this instance knows, so an operator can find the id an
// instance grant hangs off. Ordered by provider then subject so two runs diff cleanly.
func (q *Queries) ListIdentities(ctx context.Context) ([]ListIdentitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIdentitiesRow{}
	for rows.Next() {
		var i ListIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Subject,
			&i.DisplayName,
			&i.BlockedAt,
			&i.BlockedByMembershipID,
			&i.BlockReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockIdentity = `-- name: UnblockIdentity :one
UPDATE identity
SET blocked_at = NULL, blocked_by_membership_id = NULL, block_reason = NULL,
    updated_at = ?1
WHERE id = ?2
RETURNING id, provider_id, subject, display_name, blocked_at, blocked_by_membership_id, block_reason, created_at, updated_at
`

type UnblockIdentityParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) UnblockIdentity(ctx context.Context, arg UnblockIdentityParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, unblockIdentity, arg.UpdatedAt, arg.ID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Subject,
		&i.DisplayName,
		&i.BlockedAt,
		&i.BlockedByMembershipID,
		&i.BlockReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
