// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_provider.sql

package sqlitegen

import (
	"context"
)

const createIdentityProvider = `-- name: CreateIdentityProvider :one

INSERT INTO identity_provider (
  id, key, kind, display_name, enabled, verifiable_subject,
  issuer, authorization_endpoint, jwks_uri, subject_claim,
  client_id, client_secret, redirect_uri, token_endpoint, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8,
  ?9, ?10, ?11, ?12,
  ?13, ?14, ?15, ?16
)
RETURNING id, "key", kind, display_name, enabled, verifiable_subject, issuer, authorization_endpoint, jwks_uri, subject_claim, client_id, client_secret, redirect_uri, token_endpoint, created_at, updated_at
`

type CreateIdentityProviderParams struct {
	ID                    string
	Key                   string
	Kind                  string
	DisplayName           string
	Enabled               int64
	VerifiableSubject     int64
	Issuer                *string
	AuthorizationEndpoint *string
	JwksUri               *string
	SubjectClaim          *string
	ClientID              *string
	ClientSecret          *string
	RedirectUri           *string
	TokenEndpoint         *string
	CreatedAt             int64
	UpdatedAt             int64
}

// identity_provider - the pluggable IdP registry. Instance-level, mutable under
// instance.security.manage (session + step-up).
func (q *Queries) CreateIdentityProvider(ctx context.Context, arg CreateIdentityProviderParams) (IdentityProvider, error) {
	row := q.db.QueryRowContext(ctx, createIdentityProvider,
		arg.ID,
		arg.Key,
		arg.Kind,
		arg.DisplayName,
		arg.Enabled,
		arg.VerifiableSubject,
		arg.Issuer,
		arg.AuthorizationEndpoint,
		arg.JwksUri,
		arg.SubjectClaim,
		arg.ClientID,
		arg.ClientSecret,
		arg.RedirectUri,
		arg.TokenEndpoint,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Kind,
		&i.DisplayName,
		&i.Enabled,
		&i.VerifiableSubject,
		&i.Issuer,
		&i.AuthorizationEndpoint,
		&i.JwksUri,
		&i.SubjectClaim,
		&i.ClientID,
		&i.ClientSecret,
		&i.RedirectUri,
		&i.TokenEndpoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIdentityProvider = `-- name: DeleteIdentityProvider :exec
DELETE FROM identity_provider WHERE id = ?1
`

// Foreign keys are NO ACTION everywhere, so this is REFUSED once any identity, auth flow,
// credential ticket or circle references the row. That is the correct outcome: removing a provider
// people joined through would orphan their identities, and disabling it is the operation that
// actually stops new joins.
func (q *Queries) DeleteIdentityProvider(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteIdentityProvider, id)
	return err
}

const getIdentityProvider = `-- name: GetIdentityProvider :one
SELECT id, "key", kind, display_name, enabled, verifiable_subject, issuer, authorization_endpoint, jwks_uri, subject_claim, client_id, client_secret, redirect_uri, token_endpoint, created_at, updated_at FROM identity_provider WHERE id = ?1
`

func (q *Queries) GetIdentityProvider(ctx context.Context, id string) (IdentityProvider, error) {
	row := q.db.QueryRowContext(ctx, getIdentityProvider, id)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Kind,
		&i.DisplayName,
		&i.Enabled,
		&i.VerifiableSubject,
		&i.Issuer,
		&i.AuthorizationEndpoint,
		&i.JwksUri,
		&i.SubjectClaim,
		&i.ClientID,
		&i.ClientSecret,
		&i.RedirectUri,
		&i.TokenEndpoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityProviderByKey = `-- name: GetIdentityProviderByKey :one
SELECT id, "key", kind, display_name, enabled, verifiable_subject, issuer, authorization_endpoint, jwks_uri, subject_claim, client_id, client_secret, redirect_uri, token_endpoint, created_at, updated_at FROM identity_provider WHERE key = ?1
`

func (q *Queries) GetIdentityProviderByKey(ctx context.Context, key string) (IdentityProvider, error) {
	row := q.db.QueryRowContext(ctx, getIdentityProviderByKey, key)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Kind,
		&i.DisplayName,
		&i.Enabled,
		&i.VerifiableSubject,
		&i.Issuer,
		&i.AuthorizationEndpoint,
		&i.JwksUri,
		&i.SubjectClaim,
		&i.ClientID,
		&i.ClientSecret,
		&i.RedirectUri,
		&i.TokenEndpoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledIdentityProviders = `-- name: ListEnabledIdentityProviders :many
SELECT id, "key", kind, display_name, enabled, verifiable_subject, issuer, authorization_endpoint, jwks_uri, subject_claim, client_id, client_secret, redirect_uri, token_endpoint, created_at, updated_at FROM identity_provider WHERE enabled = 1 ORDER BY key
`

func (q *Queries) ListEnabledIdentityProviders(ctx context.Context) ([]IdentityProvider, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledIdentityProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityProvider{}
	for rows.Next() {
		var i IdentityProvider
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Kind,
			&i.DisplayName,
			&i.Enabled,
			&i.VerifiableSubject,
			&i.Issuer,
			&i.AuthorizationEndpoint,
			&i.JwksUri,
			&i.SubjectClaim,
			&i.ClientID,
			&i.ClientSecret,
			&i.RedirectUri,
			&i.TokenEndpoint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityProviders = `-- name: ListIdentityProviders :many
SELECT id, "key", kind, display_name, enabled, verifiable_subject, issuer, authorization_endpoint, jwks_uri, subject_claim, client_id, client_secret, redirect_uri, token_endpoint, created_at, updated_at FROM identity_provider ORDER BY key
`

func (q *Queries) ListIdentityProviders(ctx context.Context) ([]IdentityProvider, error) {
	rows, err := q.db.QueryContext(ctx, listIdentityProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityProvider{}
	for rows.Next() {
		var i IdentityProvider
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Kind,
			&i.DisplayName,
			&i.Enabled,
			&i.VerifiableSubject,
			&i.Issuer,
			&i.AuthorizationEndpoint,
			&i.JwksUri,
			&i.SubjectClaim,
			&i.ClientID,
			&i.ClientSecret,
			&i.RedirectUri,
			&i.TokenEndpoint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIdentityProviderEnabled = `-- name: SetIdentityProviderEnabled :one
UPDATE identity_provider
SET enabled = ?1, updated_at = ?2
WHERE id = ?3
RETURNING id, "key", kind, display_name, enabled, verifiable_subject, issuer, authorization_endpoint, jwks_uri, subject_claim, client_id, client_secret, redirect_uri, token_endpoint, created_at, updated_at
`

type SetIdentityProviderEnabledParams struct {
	Enabled   int64
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetIdentityProviderEnabled(ctx context.Context, arg SetIdentityProviderEnabledParams) (IdentityProvider, error) {
	row := q.db.QueryRowContext(ctx, setIdentityProviderEnabled, arg.Enabled, arg.UpdatedAt, arg.ID)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Kind,
		&i.DisplayName,
		&i.Enabled,
		&i.VerifiableSubject,
		&i.Issuer,
		&i.AuthorizationEndpoint,
		&i.JwksUri,
		&i.SubjectClaim,
		&i.ClientID,
		&i.ClientSecret,
		&i.RedirectUri,
		&i.TokenEndpoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIdentityProvider = `-- name: UpdateIdentityProvider :one
UPDATE identity_provider
SET display_name = ?1,
    enabled = ?2,
    issuer = ?3,
    authorization_endpoint = ?4,
    jwks_uri = ?5,
    subject_claim = ?6,
    client_id = ?7,
    client_secret = ?8,
    redirect_uri = ?9,
    token_endpoint = ?10,
    updated_at = ?11
WHERE id = ?12
RETURNING id, "key", kind, display_name, enabled, verifiable_subject, issuer, authorization_endpoint, jwks_uri, subject_claim, client_id, client_secret, redirect_uri, token_endpoint, created_at, updated_at
`

type UpdateIdentityProviderParams struct {
	DisplayName           string
	Enabled               int64
	Issuer                *string
	AuthorizationEndpoint *string
	JwksUri               *string
	SubjectClaim          *string
	ClientID              *string
	ClientSecret          *string
	RedirectUri           *string
	TokenEndpoint         *string
	UpdatedAt             int64
	ID                    string
}

// `key` and `kind` are absent on purpose: kind decides verifiable_subject through a CHECK, and a
// circle's revocation strength hangs off that, so changing it under a circle that already accepts
// the provider would silently restate what revocation means there. The edge answers
// 422 field_immutable instead.
func (q *Queries) UpdateIdentityProvider(ctx context.Context, arg UpdateIdentityProviderParams) (IdentityProvider, error) {
	row := q.db.QueryRowContext(ctx, updateIdentityProvider,
		arg.DisplayName,
		arg.Enabled,
		arg.Issuer,
		arg.AuthorizationEndpoint,
		arg.JwksUri,
		arg.SubjectClaim,
		arg.ClientID,
		arg.ClientSecret,
		arg.RedirectUri,
		arg.TokenEndpoint,
		arg.UpdatedAt,
		arg.ID,
	)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Kind,
		&i.DisplayName,
		&i.Enabled,
		&i.VerifiableSubject,
		&i.Issuer,
		&i.AuthorizationEndpoint,
		&i.JwksUri,
		&i.SubjectClaim,
		&i.ClientID,
		&i.ClientSecret,
		&i.RedirectUri,
		&i.TokenEndpoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
