// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package sqlitegen

import (
	"context"
)

const createInstance = `-- name: CreateInstance :one
INSERT INTO instance (
  id, name, public_url, timezone, self_service_circle_creation, created_at, updated_at
) VALUES (
  1, ?1, ?2, ?3,
  ?4, ?5, ?6
)
RETURNING id, name, public_url, timezone, self_service_circle_creation, created_at, updated_at
`

type CreateInstanceParams struct {
	Name                      string
	PublicUrl                 string
	Timezone                  string
	SelfServiceCircleCreation int64
	CreatedAt                 int64
	UpdatedAt                 int64
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, createInstance,
		arg.Name,
		arg.PublicUrl,
		arg.Timezone,
		arg.SelfServiceCircleCreation,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicUrl,
		&i.Timezone,
		&i.SelfServiceCircleCreation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstance = `-- name: GetInstance :one

SELECT id, name, public_url, timezone, self_service_circle_creation, created_at, updated_at FROM instance WHERE id = 1
`

// instance - the singleton. Every query names id = 1 rather than trusting the CHECK, so a read
// that somehow found a second row would return nothing rather than an arbitrary one.
func (q *Queries) GetInstance(ctx context.Context) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstance)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicUrl,
		&i.Timezone,
		&i.SelfServiceCircleCreation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstance = `-- name: UpdateInstance :one
UPDATE instance
SET name = ?1,
    public_url = ?2,
    timezone = ?3,
    self_service_circle_creation = ?4,
    updated_at = ?5
WHERE id = 1
RETURNING id, name, public_url, timezone, self_service_circle_creation, created_at, updated_at
`

type UpdateInstanceParams struct {
	Name                      string
	PublicUrl                 string
	Timezone                  string
	SelfServiceCircleCreation int64
	UpdatedAt                 int64
}

func (q *Queries) UpdateInstance(ctx context.Context, arg UpdateInstanceParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, updateInstance,
		arg.Name,
		arg.PublicUrl,
		arg.Timezone,
		arg.SelfServiceCircleCreation,
		arg.UpdatedAt,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicUrl,
		&i.Timezone,
		&i.SelfServiceCircleCreation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
