// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_grant.sql

package sqlitegen

import (
	"context"
)

const appendInstanceGrant = `-- name: AppendInstanceGrant :one

INSERT INTO instance_grant (
  id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason,
  prev_hash, hash, decided_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10
)
RETURNING id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason, prev_hash, hash, decided_at
`

type AppendInstanceGrantParams struct {
	ID                  string
	IdentityID          string
	Permission          string
	Decision            string
	SupersedesID        *string
	DecidedByIdentityID *string
	Reason              string
	PrevHash            []byte
	Hash                []byte
	DecidedAt           int64
}

// instance_grant - APPEND-ONLY, hash-chained. No UPDATE and no DELETE: a revocation is a new row
// naming the row it supersedes, so the decision to take a permission away is as durable as the
// decision to give it. ADR-0012.
func (q *Queries) AppendInstanceGrant(ctx context.Context, arg AppendInstanceGrantParams) (InstanceGrant, error) {
	row := q.db.QueryRowContext(ctx, appendInstanceGrant,
		arg.ID,
		arg.IdentityID,
		arg.Permission,
		arg.Decision,
		arg.SupersedesID,
		arg.DecidedByIdentityID,
		arg.Reason,
		arg.PrevHash,
		arg.Hash,
		arg.DecidedAt,
	)
	var i InstanceGrant
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Permission,
		&i.Decision,
		&i.SupersedesID,
		&i.DecidedByIdentityID,
		&i.Reason,
		&i.PrevHash,
		&i.Hash,
		&i.DecidedAt,
	)
	return i, err
}

const getInstanceGrantDecision = `-- name: GetInstanceGrantDecision :many
SELECT id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason, prev_hash, hash, decided_at FROM instance_grant AS g
WHERE g.identity_id = ?1
  AND g.permission = ?2
  AND NOT EXISTS (SELECT 1 FROM instance_grant AS s WHERE s.supersedes_id = g.id)
`

type GetInstanceGrantDecisionParams struct {
	IdentityID string
	Permission string
}

// The CURRENT decision for one identity and one permission: the row nothing supersedes.
//
// ux_instance_grant_supersedes and ux_instance_grant_head make that row unique by construction, so
// this needs no ORDER BY and no tie-break. It returns MANY rather than one on purpose: a :one
// query is a QueryRow, which scans the first row and discards the rest, so a forked chain would be
// resolved by silently picking a branch. The caller asserts the count instead.
func (q *Queries) GetInstanceGrantDecision(ctx context.Context, arg GetInstanceGrantDecisionParams) ([]InstanceGrant, error) {
	rows, err := q.db.QueryContext(ctx, getInstanceGrantDecision, arg.IdentityID, arg.Permission)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceGrant{}
	for rows.Next() {
		var i InstanceGrant
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Permission,
			&i.Decision,
			&i.SupersedesID,
			&i.DecidedByIdentityID,
			&i.Reason,
			&i.PrevHash,
			&i.Hash,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const instanceGrantExists = `-- name: InstanceGrantExists :one
SELECT EXISTS (SELECT 1 FROM instance_grant) AS any_row
`

// Whether the ledger holds any row at all, so an empty chain tail can be told apart from a chain
// with no tail. The first is the first append; the second is a cycle, which needs a hand-written
// INSERT and must not be answered by starting a second chain beside the one already there.
func (q *Queries) InstanceGrantExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, instanceGrantExists)
	var any_row bool
	err := row.Scan(&any_row)
	return any_row, err
}

const listInstanceGrantChainTail = `-- name: ListInstanceGrantChainTail :many
SELECT id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason, prev_hash, hash, decided_at FROM instance_grant AS g
WHERE NOT EXISTS (SELECT 1 FROM instance_grant AS s WHERE s.prev_hash = g.hash)
`

// The tail of the hash chain, so the next decision can name its predecessor: the row whose hash no
// other row claims as its `prev_hash`. One chain for the whole table, because an instance grant
// belongs to no circle and there is nothing to partition it by.
//
// IT IS DERIVED FROM THE CHAIN AND NEVER FROM `ORDER BY id`. A ULID is monotonic within one
// generator and `tod-serve instance grant` builds a fresh one per invocation, so two invocations
// inside one millisecond mint from random entropy and the later row can sort BELOW the earlier
// one. An id-ordered head then keeps returning the earlier row forever, the next append reuses a
// `prev_hash` that is already claimed, and `ux_instance_grant_chain` refuses it: the ledger becomes
// permanently unappendable, which is an instance nobody can administer.
//
// MANY rather than one, for the same reason GetInstanceGrantDecision is: a `:one` query is a
// QueryRow, which scans the first row and discards the rest, so a forked chain would be resolved
// by silently picking a branch. The caller asserts the count instead.
func (q *Queries) ListInstanceGrantChainTail(ctx context.Context) ([]InstanceGrant, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceGrantChainTail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceGrant{}
	for rows.Next() {
		var i InstanceGrant
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Permission,
			&i.Decision,
			&i.SupersedesID,
			&i.DecidedByIdentityID,
			&i.Reason,
			&i.PrevHash,
			&i.Hash,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceGrantDecisions = `-- name: ListInstanceGrantDecisions :many
SELECT id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason, prev_hash, hash, decided_at FROM instance_grant AS g
WHERE NOT EXISTS (SELECT 1 FROM instance_grant AS s WHERE s.supersedes_id = g.id)
ORDER BY g.identity_id, g.permission
`

// Every current decision on the instance, for the console listing. Ordered by identity then
// permission so two runs of `tod-serve instance grants` diff cleanly.
func (q *Queries) ListInstanceGrantDecisions(ctx context.Context) ([]InstanceGrant, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceGrantDecisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceGrant{}
	for rows.Next() {
		var i InstanceGrant
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Permission,
			&i.Decision,
			&i.SupersedesID,
			&i.DecidedByIdentityID,
			&i.Reason,
			&i.PrevHash,
			&i.Hash,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceGrantDecisionsForIdentity = `-- name: ListInstanceGrantDecisionsForIdentity :many
SELECT id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason, prev_hash, hash, decided_at FROM instance_grant AS g
WHERE g.identity_id = ?1
  AND NOT EXISTS (SELECT 1 FROM instance_grant AS s WHERE s.supersedes_id = g.id)
ORDER BY g.permission
`

// Every current decision for one identity, granted and revoked alike. The caller keeps the granted
// ones; filtering here would put the value of instance_grant.decision in two places.
func (q *Queries) ListInstanceGrantDecisionsForIdentity(ctx context.Context, identityID string) ([]InstanceGrant, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceGrantDecisionsForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceGrant{}
	for rows.Next() {
		var i InstanceGrant
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Permission,
			&i.Decision,
			&i.SupersedesID,
			&i.DecidedByIdentityID,
			&i.Reason,
			&i.PrevHash,
			&i.Hash,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceGrantHistory = `-- name: ListInstanceGrantHistory :many
SELECT id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason, prev_hash, hash, decided_at FROM instance_grant ORDER BY decided_at, id
`

// Every decision ever recorded, oldest first: the audit read. Nothing prunes this.
//
// Ordered by `decided_at` and only then by id, because id order is per-generator: two console
// invocations inside one millisecond mint from random entropy, and ordering by id alone would
// report them in the wrong order. `decided_at` is Micros, so the tie-break is reached only for two
// decisions in the same MICROsecond, where the ledger genuinely does not know which came first.
func (q *Queries) ListInstanceGrantHistory(ctx context.Context) ([]InstanceGrant, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceGrantHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceGrant{}
	for rows.Next() {
		var i InstanceGrant
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Permission,
			&i.Decision,
			&i.SupersedesID,
			&i.DecidedByIdentityID,
			&i.Reason,
			&i.PrevHash,
			&i.Hash,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
