// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_grant.sql

package sqlitegen

import (
	"context"
)

const appendInstanceGrant = `-- name: AppendInstanceGrant :one

INSERT INTO instance_grant (
  id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason,
  prev_hash, hash, decided_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10
)
RETURNING id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason, prev_hash, hash, decided_at
`

type AppendInstanceGrantParams struct {
	ID                  string
	IdentityID          string
	Permission          string
	Decision            string
	SupersedesID        *string
	DecidedByIdentityID *string
	Reason              string
	PrevHash            []byte
	Hash                []byte
	DecidedAt           int64
}

// instance_grant - APPEND-ONLY, hash-chained. No UPDATE and no DELETE: a revocation is a new row
// naming the row it supersedes, so the decision to take a permission away is as durable as the
// decision to give it. ADR-0012.
func (q *Queries) AppendInstanceGrant(ctx context.Context, arg AppendInstanceGrantParams) (InstanceGrant, error) {
	row := q.db.QueryRowContext(ctx, appendInstanceGrant,
		arg.ID,
		arg.IdentityID,
		arg.Permission,
		arg.Decision,
		arg.SupersedesID,
		arg.DecidedByIdentityID,
		arg.Reason,
		arg.PrevHash,
		arg.Hash,
		arg.DecidedAt,
	)
	var i InstanceGrant
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Permission,
		&i.Decision,
		&i.SupersedesID,
		&i.DecidedByIdentityID,
		&i.Reason,
		&i.PrevHash,
		&i.Hash,
		&i.DecidedAt,
	)
	return i, err
}

const getInstanceGrantDecision = `-- name: GetInstanceGrantDecision :one
SELECT id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason, prev_hash, hash, decided_at FROM instance_grant AS g
WHERE g.identity_id = ?1
  AND g.permission = ?2
  AND NOT EXISTS (SELECT 1 FROM instance_grant AS s WHERE s.supersedes_id = g.id)
`

type GetInstanceGrantDecisionParams struct {
	IdentityID string
	Permission string
}

// The CURRENT decision for one identity and one permission: the row nothing supersedes.
//
// ux_instance_grant_supersedes and ux_instance_grant_head make that row unique by construction, so
// this needs no ORDER BY and no tie-break. A LIMIT here would hide a forked chain rather than let
// the caller find out about it.
func (q *Queries) GetInstanceGrantDecision(ctx context.Context, arg GetInstanceGrantDecisionParams) (InstanceGrant, error) {
	row := q.db.QueryRowContext(ctx, getInstanceGrantDecision, arg.IdentityID, arg.Permission)
	var i InstanceGrant
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Permission,
		&i.Decision,
		&i.SupersedesID,
		&i.DecidedByIdentityID,
		&i.Reason,
		&i.PrevHash,
		&i.Hash,
		&i.DecidedAt,
	)
	return i, err
}

const getLatestInstanceGrant = `-- name: GetLatestInstanceGrant :one
SELECT id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason, prev_hash, hash, decided_at FROM instance_grant ORDER BY id DESC LIMIT 1
`

// The tail of the hash chain, so the next decision can name its predecessor. One chain for the
// whole table: an instance grant belongs to no circle, so there is nothing to partition it by.
func (q *Queries) GetLatestInstanceGrant(ctx context.Context) (InstanceGrant, error) {
	row := q.db.QueryRowContext(ctx, getLatestInstanceGrant)
	var i InstanceGrant
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Permission,
		&i.Decision,
		&i.SupersedesID,
		&i.DecidedByIdentityID,
		&i.Reason,
		&i.PrevHash,
		&i.Hash,
		&i.DecidedAt,
	)
	return i, err
}

const listInstanceGrantDecisions = `-- name: ListInstanceGrantDecisions :many
SELECT id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason, prev_hash, hash, decided_at FROM instance_grant AS g
WHERE NOT EXISTS (SELECT 1 FROM instance_grant AS s WHERE s.supersedes_id = g.id)
ORDER BY g.identity_id, g.permission
`

// Every current decision on the instance, for the console listing. Ordered by identity then
// permission so two runs of `tod-serve instance grants` diff cleanly.
func (q *Queries) ListInstanceGrantDecisions(ctx context.Context) ([]InstanceGrant, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceGrantDecisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceGrant{}
	for rows.Next() {
		var i InstanceGrant
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Permission,
			&i.Decision,
			&i.SupersedesID,
			&i.DecidedByIdentityID,
			&i.Reason,
			&i.PrevHash,
			&i.Hash,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceGrantDecisionsForIdentity = `-- name: ListInstanceGrantDecisionsForIdentity :many
SELECT id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason, prev_hash, hash, decided_at FROM instance_grant AS g
WHERE g.identity_id = ?1
  AND NOT EXISTS (SELECT 1 FROM instance_grant AS s WHERE s.supersedes_id = g.id)
ORDER BY g.permission
`

// Every current decision for one identity, granted and revoked alike. The caller keeps the granted
// ones; filtering here would put the value of instance_grant.decision in two places.
func (q *Queries) ListInstanceGrantDecisionsForIdentity(ctx context.Context, identityID string) ([]InstanceGrant, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceGrantDecisionsForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceGrant{}
	for rows.Next() {
		var i InstanceGrant
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Permission,
			&i.Decision,
			&i.SupersedesID,
			&i.DecidedByIdentityID,
			&i.Reason,
			&i.PrevHash,
			&i.Hash,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceGrantHistory = `-- name: ListInstanceGrantHistory :many
SELECT id, identity_id, permission, decision, supersedes_id, decided_by_identity_id, reason, prev_hash, hash, decided_at FROM instance_grant ORDER BY id
`

// Every decision ever recorded, oldest first: the audit read. Nothing prunes this.
func (q *Queries) ListInstanceGrantHistory(ctx context.Context) ([]InstanceGrant, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceGrantHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceGrant{}
	for rows.Next() {
		var i InstanceGrant
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Permission,
			&i.Decision,
			&i.SupersedesID,
			&i.DecidedByIdentityID,
			&i.Reason,
			&i.PrevHash,
			&i.Hash,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
