// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite.sql

package sqlitegen

import (
	"context"
)

const consumeInvite = `-- name: ConsumeInvite :one
UPDATE invite
SET uses = uses + 1, updated_at = ?1
WHERE circle_id = ?2 AND id = ?3
  AND revoked_at IS NULL AND expires_at > ?4 AND uses < max_uses
RETURNING id, circle_id, code_hash, code_prefix, role, max_uses, uses, expires_at, revoked_at, created_by_membership_id, minted_by_kind, note, created_at, updated_at
`

type ConsumeInviteParams struct {
	UpdatedAt int64
	CircleID  string
	ID        string
	Now       int64
}

// The CHECK (uses <= max_uses) makes over-redemption unrepresentable; `uses < max_uses` here turns
// the race into a returned-no-row rather than a constraint violation surfacing as a 500.
func (q *Queries) ConsumeInvite(ctx context.Context, arg ConsumeInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, consumeInvite,
		arg.UpdatedAt,
		arg.CircleID,
		arg.ID,
		arg.Now,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.CodeHash,
		&i.CodePrefix,
		&i.Role,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByMembershipID,
		&i.MintedByKind,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countLiveInvites = `-- name: CountLiveInvites :one
SELECT COUNT(*) AS live FROM invite
WHERE circle_id = ?1
  AND revoked_at IS NULL AND expires_at > ?2 AND uses < max_uses
`

type CountLiveInvitesParams struct {
	CircleID string
	Now      int64
}

// The `active_invite_count` revokeMember returns, so the UI can say "you also have 2 live
// invites" without a second warnings channel being invented for it.
func (q *Queries) CountLiveInvites(ctx context.Context, arg CountLiveInvitesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveInvites, arg.CircleID, arg.Now)
	var live int64
	err := row.Scan(&live)
	return live, err
}

const createInvite = `-- name: CreateInvite :one

INSERT INTO invite (
  id, circle_id, code_hash, code_prefix, role, max_uses, uses, expires_at,
  created_by_membership_id, minted_by_kind, note, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, 0, ?7, ?8,
  ?9, ?10, ?11, ?12
)
RETURNING id, circle_id, code_hash, code_prefix, role, max_uses, uses, expires_at, revoked_at, created_by_membership_id, minted_by_kind, note, created_at, updated_at
`

type CreateInviteParams struct {
	ID                    string
	CircleID              string
	CodeHash              []byte
	CodePrefix            string
	Role                  string
	MaxUses               int64
	ExpiresAt             int64
	CreatedByMembershipID string
	MintedByKind          string
	Note                  string
	CreatedAt             int64
	UpdatedAt             int64
}

// invite - codes are INSTANCE-unique, so POST /join needs no circle id: one paste.
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.ID,
		arg.CircleID,
		arg.CodeHash,
		arg.CodePrefix,
		arg.Role,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.CreatedByMembershipID,
		arg.MintedByKind,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.CodeHash,
		&i.CodePrefix,
		&i.Role,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByMembershipID,
		&i.MintedByKind,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id, circle_id, code_hash, code_prefix, role, max_uses, uses, expires_at, revoked_at, created_by_membership_id, minted_by_kind, note, created_at, updated_at FROM invite WHERE circle_id = ?1 AND id = ?2
`

type GetInviteParams struct {
	CircleID string
	ID       string
}

func (q *Queries) GetInvite(ctx context.Context, arg GetInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInvite, arg.CircleID, arg.ID)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.CodeHash,
		&i.CodePrefix,
		&i.Role,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByMembershipID,
		&i.MintedByKind,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInviteByCodeHash = `-- name: GetInviteByCodeHash :one
SELECT id, circle_id, code_hash, code_prefix, role, max_uses, uses, expires_at, revoked_at, created_by_membership_id, minted_by_kind, note, created_at, updated_at FROM invite WHERE code_hash = ?1
`

// tenancy: an invite code is instance-unique and IS the capability - holding it is the evidence
// that somebody handed it to you. previewInvite and /join resolve the circle FROM this row, so
// naming a circle here would require the caller to supply one, which is the oracle canonical section 7
// exists to close. Looked up by hash on the unique index, NEVER by prefix: a prefix lookup is a
// brute-force oracle.
func (q *Queries) GetInviteByCodeHash(ctx context.Context, codeHash []byte) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByCodeHash, codeHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.CodeHash,
		&i.CodePrefix,
		&i.Role,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByMembershipID,
		&i.MintedByKind,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, circle_id, code_hash, code_prefix, role, max_uses, uses, expires_at, revoked_at, created_by_membership_id, minted_by_kind, note, created_at, updated_at FROM invite WHERE circle_id = ?1 ORDER BY id DESC
`

func (q *Queries) ListInvites(ctx context.Context, circleID string) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listInvites, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.CodeHash,
			&i.CodePrefix,
			&i.Role,
			&i.MaxUses,
			&i.Uses,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedByMembershipID,
			&i.MintedByKind,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :one
UPDATE invite
SET revoked_at = ?1, updated_at = ?2
WHERE circle_id = ?3 AND id = ?4 AND revoked_at IS NULL
RETURNING id, circle_id, code_hash, code_prefix, role, max_uses, uses, expires_at, revoked_at, created_by_membership_id, minted_by_kind, note, created_at, updated_at
`

type RevokeInviteParams struct {
	RevokedAt *int64
	UpdatedAt int64
	CircleID  string
	ID        string
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, revokeInvite,
		arg.RevokedAt,
		arg.UpdatedAt,
		arg.CircleID,
		arg.ID,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.CodeHash,
		&i.CodePrefix,
		&i.Role,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedByMembershipID,
		&i.MintedByKind,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeLiveInvitesForCircle = `-- name: RevokeLiveInvitesForCircle :execrows
UPDATE invite
SET revoked_at = ?1, updated_at = ?2
WHERE circle_id = ?3
  AND revoked_at IS NULL AND expires_at > ?4 AND uses < max_uses
`

type RevokeLiveInvitesForCircleParams struct {
	RevokedAt *int64
	UpdatedAt int64
	CircleID  string
	Now       int64
}

// When a weakly-revocable member is revoked and revoke_invalidates_invites = 1, every outstanding
// invite goes in the SAME transaction. The officers' false belief that revocation worked is the
// damage, not the re-entry.
//
// The predicate is the same one CountLiveInvites uses, and it has to be: the row count this
// returns is reported to an officer as "2 invites were revoked", and an UPDATE that also touched
// expired and exhausted rows would report a number larger than the number of doors it closed.
func (q *Queries) RevokeLiveInvitesForCircle(ctx context.Context, arg RevokeLiveInvitesForCircleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeLiveInvitesForCircle,
		arg.RevokedAt,
		arg.UpdatedAt,
		arg.CircleID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
