// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite_redemption.sql

package sqlitegen

import (
	"context"
)

const createInviteRedemption = `-- name: CreateInviteRedemption :one

INSERT INTO invite_redemption (id, circle_id, invite_id, membership_id, identity_id, created_at)
VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6
)
RETURNING id, circle_id, invite_id, membership_id, identity_id, created_at
`

type CreateInviteRedemptionParams struct {
	ID           string
	CircleID     string
	InviteID     string
	MembershipID string
	IdentityID   *string
	CreatedAt    int64
}

// invite_redemption - append-only: who redeemed what, when. No UPDATE, no DELETE.
func (q *Queries) CreateInviteRedemption(ctx context.Context, arg CreateInviteRedemptionParams) (InviteRedemption, error) {
	row := q.db.QueryRowContext(ctx, createInviteRedemption,
		arg.ID,
		arg.CircleID,
		arg.InviteID,
		arg.MembershipID,
		arg.IdentityID,
		arg.CreatedAt,
	)
	var i InviteRedemption
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.InviteID,
		&i.MembershipID,
		&i.IdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const listInviteRedemptions = `-- name: ListInviteRedemptions :many
SELECT id, circle_id, invite_id, membership_id, identity_id, created_at FROM invite_redemption
WHERE circle_id = ?1 AND invite_id = ?2
ORDER BY id
`

type ListInviteRedemptionsParams struct {
	CircleID string
	InviteID string
}

func (q *Queries) ListInviteRedemptions(ctx context.Context, arg ListInviteRedemptionsParams) ([]InviteRedemption, error) {
	rows, err := q.db.QueryContext(ctx, listInviteRedemptions, arg.CircleID, arg.InviteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InviteRedemption{}
	for rows.Next() {
		var i InviteRedemption
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.InviteID,
			&i.MembershipID,
			&i.IdentityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
