// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package sqlitegen

import (
	"context"
)

const createMembership = `-- name: CreateMembership :one

INSERT INTO membership (
  id, circle_id, identity_id, kind, owner_membership_id, display_name, display_name_norm,
  role, admitted_by_invite_id, joined_at, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10,
  ?11, ?12
)
RETURNING id, circle_id, identity_id, kind, owner_membership_id, display_name, display_name_norm, role, admitted_by_invite_id, joined_at, revoked_at, revoked_by_membership_id, revoke_reason, created_at, updated_at
`

type CreateMembershipParams struct {
	ID                 string
	CircleID           string
	IdentityID         *string
	Kind               string
	OwnerMembershipID  *string
	DisplayName        string
	DisplayNameNorm    string
	Role               string
	AdmittedByInviteID *string
	JoinedAt           int64
	CreatedAt          int64
	UpdatedAt          int64
}

// membership - (circle, identity) -> role and revocation.
//
// There is NO delete-membership query, at any permission level, and there never will be: the
// partial unique index is the entire revocation mechanism, and a delete-then-insert path would let
// a revoked person rejoin as a fresh row.
func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, createMembership,
		arg.ID,
		arg.CircleID,
		arg.IdentityID,
		arg.Kind,
		arg.OwnerMembershipID,
		arg.DisplayName,
		arg.DisplayNameNorm,
		arg.Role,
		arg.AdmittedByInviteID,
		arg.JoinedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.IdentityID,
		&i.Kind,
		&i.OwnerMembershipID,
		&i.DisplayName,
		&i.DisplayNameNorm,
		&i.Role,
		&i.AdmittedByInviteID,
		&i.JoinedAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, circle_id, identity_id, kind, owner_membership_id, display_name, display_name_norm, role, admitted_by_invite_id, joined_at, revoked_at, revoked_by_membership_id, revoke_reason, created_at, updated_at FROM membership WHERE circle_id = ?1 AND id = ?2
`

type GetMembershipParams struct {
	CircleID string
	ID       string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, getMembership, arg.CircleID, arg.ID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.IdentityID,
		&i.Kind,
		&i.OwnerMembershipID,
		&i.DisplayName,
		&i.DisplayNameNorm,
		&i.Role,
		&i.AdmittedByInviteID,
		&i.JoinedAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT id, circle_id, identity_id, kind, owner_membership_id, display_name, display_name_norm, role, admitted_by_invite_id, joined_at, revoked_at, revoked_by_membership_id, revoke_reason, created_at, updated_at FROM membership WHERE id = ?1
`

// tenancy: keyed on the membership a verified credential is already bound to, and this lookup is
// what RESOLVES the caller's circle -- so it cannot also filter by one. A PAT carries a membership
// id and nothing else (ADR-0005); every circle-scoped query downstream of this one is filtered by
// the circle_id this row returns, which is the only reading of the tenancy rule that terminates.
func (q *Queries) GetMembershipByID(ctx context.Context, id string) (Membership, error) {
	row := q.db.QueryRowContext(ctx, getMembershipByID, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.IdentityID,
		&i.Kind,
		&i.OwnerMembershipID,
		&i.DisplayName,
		&i.DisplayNameNorm,
		&i.Role,
		&i.AdmittedByInviteID,
		&i.JoinedAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipByIdentity = `-- name: GetMembershipByIdentity :one
SELECT id, circle_id, identity_id, kind, owner_membership_id, display_name, display_name_norm, role, admitted_by_invite_id, joined_at, revoked_at, revoked_by_membership_id, revoke_reason, created_at, updated_at FROM membership
WHERE circle_id = ?1 AND identity_id = ?2
`

type GetMembershipByIdentityParams struct {
	CircleID   string
	IdentityID *string
}

func (q *Queries) GetMembershipByIdentity(ctx context.Context, arg GetMembershipByIdentityParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, getMembershipByIdentity, arg.CircleID, arg.IdentityID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.IdentityID,
		&i.Kind,
		&i.OwnerMembershipID,
		&i.DisplayName,
		&i.DisplayNameNorm,
		&i.Role,
		&i.AdmittedByInviteID,
		&i.JoinedAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemberships = `-- name: ListMemberships :many
SELECT id, circle_id, identity_id, kind, owner_membership_id, display_name, display_name_norm, role, admitted_by_invite_id, joined_at, revoked_at, revoked_by_membership_id, revoke_reason, created_at, updated_at FROM membership WHERE circle_id = ?1 ORDER BY id
`

func (q *Queries) ListMemberships(ctx context.Context, circleID string) ([]Membership, error) {
	rows, err := q.db.QueryContext(ctx, listMemberships, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.IdentityID,
			&i.Kind,
			&i.OwnerMembershipID,
			&i.DisplayName,
			&i.DisplayNameNorm,
			&i.Role,
			&i.AdmittedByInviteID,
			&i.JoinedAt,
			&i.RevokedAt,
			&i.RevokedByMembershipID,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForIdentity = `-- name: ListMembershipsForIdentity :many
SELECT id, circle_id, identity_id, kind, owner_membership_id, display_name, display_name_norm, role, admitted_by_invite_id, joined_at, revoked_at, revoked_by_membership_id, revoke_reason, created_at, updated_at FROM membership WHERE identity_id = ?1 ORDER BY circle_id
`

// tenancy: keyed on a VERIFIED identity, never on a caller-supplied circle id. The OAuth callback
// uses it to decide which guilds need facts, and it must see every circle the identity is in.
func (q *Queries) ListMembershipsForIdentity(ctx context.Context, identityID *string) ([]Membership, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsForIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.IdentityID,
			&i.Kind,
			&i.OwnerMembershipID,
			&i.DisplayName,
			&i.DisplayNameNorm,
			&i.Role,
			&i.AdmittedByInviteID,
			&i.JoinedAt,
			&i.RevokedAt,
			&i.RevokedByMembershipID,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reinstateMembership = `-- name: ReinstateMembership :one
UPDATE membership
SET revoked_at = NULL, revoked_by_membership_id = NULL, revoke_reason = NULL,
    updated_at = ?1
WHERE circle_id = ?2 AND id = ?3
RETURNING id, circle_id, identity_id, kind, owner_membership_id, display_name, display_name_norm, role, admitted_by_invite_id, joined_at, revoked_at, revoked_by_membership_id, revoke_reason, created_at, updated_at
`

type ReinstateMembershipParams struct {
	UpdatedAt int64
	CircleID  string
	ID        string
}

// Explicit and audited, requiring member.revoke. Reinstatement is the only way back in, which is
// what makes "there is no second membership row" a rule rather than an inconvenience.
func (q *Queries) ReinstateMembership(ctx context.Context, arg ReinstateMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, reinstateMembership, arg.UpdatedAt, arg.CircleID, arg.ID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.IdentityID,
		&i.Kind,
		&i.OwnerMembershipID,
		&i.DisplayName,
		&i.DisplayNameNorm,
		&i.Role,
		&i.AdmittedByInviteID,
		&i.JoinedAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeMembership = `-- name: RevokeMembership :one
UPDATE membership
SET revoked_at = ?1,
    revoked_by_membership_id = ?2,
    revoke_reason = ?3,
    updated_at = ?4
WHERE circle_id = ?5 AND id = ?6 AND revoked_at IS NULL
RETURNING id, circle_id, identity_id, kind, owner_membership_id, display_name, display_name_norm, role, admitted_by_invite_id, joined_at, revoked_at, revoked_by_membership_id, revoke_reason, created_at, updated_at
`

type RevokeMembershipParams struct {
	RevokedAt             *int64
	RevokedByMembershipID *string
	RevokeReason          *string
	UpdatedAt             int64
	CircleID              string
	ID                    string
}

func (q *Queries) RevokeMembership(ctx context.Context, arg RevokeMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, revokeMembership,
		arg.RevokedAt,
		arg.RevokedByMembershipID,
		arg.RevokeReason,
		arg.UpdatedAt,
		arg.CircleID,
		arg.ID,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.IdentityID,
		&i.Kind,
		&i.OwnerMembershipID,
		&i.DisplayName,
		&i.DisplayNameNorm,
		&i.Role,
		&i.AdmittedByInviteID,
		&i.JoinedAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMembership = `-- name: UpdateMembership :one
UPDATE membership
SET display_name = ?1, display_name_norm = ?2,
    role = ?3, updated_at = ?4
WHERE circle_id = ?5 AND id = ?6
RETURNING id, circle_id, identity_id, kind, owner_membership_id, display_name, display_name_norm, role, admitted_by_invite_id, joined_at, revoked_at, revoked_by_membership_id, revoke_reason, created_at, updated_at
`

type UpdateMembershipParams struct {
	DisplayName     string
	DisplayNameNorm string
	Role            string
	UpdatedAt       int64
	CircleID        string
	ID              string
}

func (q *Queries) UpdateMembership(ctx context.Context, arg UpdateMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, updateMembership,
		arg.DisplayName,
		arg.DisplayNameNorm,
		arg.Role,
		arg.UpdatedAt,
		arg.CircleID,
		arg.ID,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.IdentityID,
		&i.Kind,
		&i.OwnerMembershipID,
		&i.DisplayName,
		&i.DisplayNameNorm,
		&i.Role,
		&i.AdmittedByInviteID,
		&i.JoinedAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
