// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

type ApiToken struct {
	ID                    string
	MembershipID          string
	TokenPrefix           string
	TokenHash             []byte
	Name                  string
	ScopesJson            string
	LastUsedAt            *int64
	ExpiresAt             *int64
	RevokedAt             *int64
	RevokedByMembershipID *string
	CreatedAt             int64
	UpdatedAt             int64
}

type AuditLog struct {
	ID                string
	CircleID          string
	ActorMembershipID *string
	Action            string
	EntityType        string
	EntityID          *string
	DetailJson        string
	PrevHash          []byte
	Hash              []byte
	CreatedAt         int64
}

type AuthFlow struct {
	ID             string
	State          string
	PkceVerifier   string
	ProviderID     string
	InviteCodeHash []byte
	CircleID       *string
	ExpiresAt      int64
	ConsumedAt     *int64
	CreatedAt      int64
	UpdatedAt      int64
}

type Circle struct {
	ID                       string
	Name                     string
	NameNorm                 string
	Description              string
	Server                   string
	Timezone                 string
	MinReportersToSupersede  int64
	RevokeInvalidatesInvites int64
	State                    string
	DeletedAt                *int64
	CreatedAt                int64
	UpdatedAt                int64
}

type CircleProvider struct {
	CircleID                   string
	ProviderID                 string
	DiscordGuildID             *string
	DiscordRequiredRoleIdsJson string
	CreatedAt                  int64
	UpdatedAt                  int64
}

type CircleTimerOverride struct {
	CircleID                 string
	TargetID                 string
	WindowKind               string
	WindowOpenOffsetSeconds  *int64
	WindowCloseOffsetSeconds *int64
	FixedGraceSeconds        int64
	ClusterEpsilonSeconds    *int64
	Note                     string
	CreatedByMembershipID    string
	CreatedAt                int64
	UpdatedAt                int64
}

type CredentialTicket struct {
	ID             string
	TicketHash     []byte
	ProviderID     string
	Subject        string
	DisplayName    string
	GuildRolesJson string
	ExpiresAt      int64
	ConsumedAt     *int64
	CreatedAt      int64
	UpdatedAt      int64
}

type EventOutbox struct {
	EventSeq    int64
	ID          string
	CircleID    *string
	Kind        string
	PayloadJson string
	CreatedAt   int64
}

type IdempotencyRecord struct {
	ID                    string
	PrincipalMembershipID string
	Key                   string
	RequestHash           []byte
	ResponseStatus        *int64
	ResponseBody          *string
	CompletedAt           *int64
	ExpiresAt             int64
	CreatedAt             int64
	UpdatedAt             int64
}

type Identity struct {
	ID                    string
	ProviderID            string
	Subject               string
	DisplayName           string
	BlockedAt             *int64
	BlockedByMembershipID *string
	BlockReason           *string
	CreatedAt             int64
	UpdatedAt             int64
}

type IdentityLink struct {
	ID                   string
	PrimaryIdentityID    string
	LinkedIdentityID     string
	Method               string
	LinkedByMembershipID string
	LinkedAt             int64
}

type IdentityProvider struct {
	ID                    string
	Key                   string
	Kind                  string
	DisplayName           string
	Enabled               int64
	VerifiableSubject     int64
	Issuer                *string
	AuthorizationEndpoint *string
	JwksUri               *string
	SubjectClaim          *string
	ClientID              *string
	ClientSecret          *string
	RedirectUri           *string
	TokenEndpoint         *string
	CreatedAt             int64
	UpdatedAt             int64
}

type Instance struct {
	ID                        int64
	Name                      string
	PublicUrl                 string
	Timezone                  string
	SelfServiceCircleCreation int64
	CreatedAt                 int64
	UpdatedAt                 int64
}

type InstanceGrant struct {
	ID                  string
	IdentityID          string
	Permission          string
	Decision            string
	SupersedesID        *string
	DecidedByIdentityID *string
	Reason              string
	PrevHash            []byte
	Hash                []byte
	DecidedAt           int64
}

type Invite struct {
	ID                    string
	CircleID              string
	CodeHash              []byte
	CodePrefix            string
	Role                  string
	MaxUses               int64
	Uses                  int64
	ExpiresAt             int64
	RevokedAt             *int64
	CreatedByMembershipID string
	MintedByKind          string
	Note                  string
	CreatedAt             int64
	UpdatedAt             int64
}

type InviteRedemption struct {
	ID           string
	CircleID     string
	InviteID     string
	MembershipID string
	IdentityID   *string
	CreatedAt    int64
}

type Membership struct {
	ID                    string
	CircleID              string
	IdentityID            *string
	Kind                  string
	OwnerMembershipID     *string
	DisplayName           string
	DisplayNameNorm       string
	Role                  string
	AdmittedByInviteID    *string
	JoinedAt              int64
	RevokedAt             *int64
	RevokedByMembershipID *string
	RevokeReason          *string
	CreatedAt             int64
	UpdatedAt             int64
}

type QuakeEvent struct {
	ID                     string
	CircleID               string
	OccurredAt             int64
	ReportedAt             int64
	ReportedByMembershipID string
	Source                 string
	Note                   string
}

type RaidTarget struct {
	ID            string
	Name          string
	NameNorm      string
	Zone          string
	ZoneNorm      string
	Expansion     string
	Category      string
	IsQuakeTarget int64
	State         string
	CreatedAt     int64
	UpdatedAt     int64
}

type RaidTargetAlias struct {
	ID        string
	TargetID  string
	Alias     string
	AliasNorm string
	CreatedAt int64
	UpdatedAt int64
}

type RaidTargetTimer struct {
	TargetID                 string
	Server                   string
	WindowKind               string
	WindowOpenOffsetSeconds  *int64
	WindowCloseOffsetSeconds *int64
	FixedGraceSeconds        int64
	ClusterEpsilonSeconds    *int64
	Source                   *string
	Note                     string
	CreatedAt                int64
	UpdatedAt                int64
}

type TargetStateCache struct {
	CircleID              string
	TargetID              string
	ComputedAt            int64
	LatestReportID        *string
	ReportCount           int64
	Status                string
	Confidence            string
	Contested             int64
	ContestReason         *string
	ChangeReason          *string
	DiedAt                *int64
	WindowOpenAt          *int64
	WindowCloseAt         *int64
	SpawnAt               *int64
	DistinctReporterCount int64
	LogLineCount          int64
	SpreadSeconds         *int64
	RevokedReporterCount  int64
	CreatedAt             int64
	UpdatedAt             int64
}

type TodMeta struct {
	Key       string
	Value     string
	UpdatedAt int64
}

type TodReport struct {
	ID                       string
	CircleID                 string
	TargetID                 string
	Kind                     string
	DiedAt                   int64
	ReportedAt               int64
	ReporterMembershipID     string
	Source                   string
	SelfConfidence           string
	SourceLine               *string
	SourceCharacter          *string
	LogCharacter             *string
	KilledByGuild            *string
	ClientClockOffsetSeconds *int64
	RetractsReportID         *string
}
