// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quake_event.sql

package sqlitegen

import (
	"context"
)

const createQuakeEvent = `-- name: CreateQuakeEvent :one

INSERT INTO quake_event (
  id, circle_id, occurred_at, reported_at, reported_by_membership_id, source, note
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7
)
RETURNING id, circle_id, occurred_at, reported_at, reported_by_membership_id, source, note
`

type CreateQuakeEventParams struct {
	ID                     string
	CircleID               string
	OccurredAt             int64
	ReportedAt             int64
	ReportedByMembershipID string
	Source                 string
	Note                   string
}

// quake_event - APPEND-ONLY. An earthquake repops every raid target on the server at once, and
// modelling it as N kill reports would be a lie nobody observed.
func (q *Queries) CreateQuakeEvent(ctx context.Context, arg CreateQuakeEventParams) (QuakeEvent, error) {
	row := q.db.QueryRowContext(ctx, createQuakeEvent,
		arg.ID,
		arg.CircleID,
		arg.OccurredAt,
		arg.ReportedAt,
		arg.ReportedByMembershipID,
		arg.Source,
		arg.Note,
	)
	var i QuakeEvent
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.OccurredAt,
		&i.ReportedAt,
		&i.ReportedByMembershipID,
		&i.Source,
		&i.Note,
	)
	return i, err
}

const getLatestQuakeEvent = `-- name: GetLatestQuakeEvent :one
SELECT id, circle_id, occurred_at, reported_at, reported_by_membership_id, source, note FROM quake_event
WHERE circle_id = ?1
ORDER BY occurred_at DESC
LIMIT 1
`

// The truncation point: for a quake target, every report with died_at before this moves to history
// and cannot form the current cluster.
func (q *Queries) GetLatestQuakeEvent(ctx context.Context, circleID string) (QuakeEvent, error) {
	row := q.db.QueryRowContext(ctx, getLatestQuakeEvent, circleID)
	var i QuakeEvent
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.OccurredAt,
		&i.ReportedAt,
		&i.ReportedByMembershipID,
		&i.Source,
		&i.Note,
	)
	return i, err
}

const listQuakeEvents = `-- name: ListQuakeEvents :many
SELECT id, circle_id, occurred_at, reported_at, reported_by_membership_id, source, note FROM quake_event WHERE circle_id = ?1 ORDER BY occurred_at DESC
`

func (q *Queries) ListQuakeEvents(ctx context.Context, circleID string) ([]QuakeEvent, error) {
	rows, err := q.db.QueryContext(ctx, listQuakeEvents, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuakeEvent{}
	for rows.Next() {
		var i QuakeEvent
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.OccurredAt,
			&i.ReportedAt,
			&i.ReportedByMembershipID,
			&i.Source,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
