// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raid_target.sql

package sqlitegen

import (
	"context"
)

const createRaidTarget = `-- name: CreateRaidTarget :one

INSERT INTO raid_target (
  id, name, name_norm, zone, zone_norm, expansion, category, is_quake_target, state,
  created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8, ?9,
  ?10, ?11
)
RETURNING id, name, name_norm, zone, zone_norm, expansion, category, is_quake_target, state, created_at, updated_at
`

type CreateRaidTargetParams struct {
	ID            string
	Name          string
	NameNorm      string
	Zone          string
	ZoneNorm      string
	Expansion     string
	Category      string
	IsQuakeTarget int64
	State         string
	CreatedAt     int64
	UpdatedAt     int64
}

// raid_target - the catalogue. Instance-wide, not circle-scoped: a mob's existence is a game fact.
// Matching is on name_norm, normalised in Go, never on a collation.
func (q *Queries) CreateRaidTarget(ctx context.Context, arg CreateRaidTargetParams) (RaidTarget, error) {
	row := q.db.QueryRowContext(ctx, createRaidTarget,
		arg.ID,
		arg.Name,
		arg.NameNorm,
		arg.Zone,
		arg.ZoneNorm,
		arg.Expansion,
		arg.Category,
		arg.IsQuakeTarget,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RaidTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNorm,
		&i.Zone,
		&i.ZoneNorm,
		&i.Expansion,
		&i.Category,
		&i.IsQuakeTarget,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRaidTarget = `-- name: GetRaidTarget :one
SELECT id, name, name_norm, zone, zone_norm, expansion, category, is_quake_target, state, created_at, updated_at FROM raid_target WHERE id = ?1
`

func (q *Queries) GetRaidTarget(ctx context.Context, id string) (RaidTarget, error) {
	row := q.db.QueryRowContext(ctx, getRaidTarget, id)
	var i RaidTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNorm,
		&i.Zone,
		&i.ZoneNorm,
		&i.Expansion,
		&i.Category,
		&i.IsQuakeTarget,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRaidTargetByNameNorm = `-- name: GetRaidTargetByNameNorm :one
SELECT id, name, name_norm, zone, zone_norm, expansion, category, is_quake_target, state, created_at, updated_at FROM raid_target WHERE name_norm = ?1
`

func (q *Queries) GetRaidTargetByNameNorm(ctx context.Context, nameNorm string) (RaidTarget, error) {
	row := q.db.QueryRowContext(ctx, getRaidTargetByNameNorm, nameNorm)
	var i RaidTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNorm,
		&i.Zone,
		&i.ZoneNorm,
		&i.Expansion,
		&i.Category,
		&i.IsQuakeTarget,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllRaidTargets = `-- name: ListAllRaidTargets :many
SELECT id, name, name_norm, zone, zone_norm, expansion, category, is_quake_target, state, created_at, updated_at FROM raid_target ORDER BY name_norm
`

// Every target, retired ones included. The resolve ladder needs the retired rows so a backdated
// report can still name a target by its exact name, and the catalogue is tens of rows, not tens of
// thousands, so it is read whole rather than matched with a LIKE that would be a second
// normalisation path beside core.Normalise.
func (q *Queries) ListAllRaidTargets(ctx context.Context) ([]RaidTarget, error) {
	rows, err := q.db.QueryContext(ctx, listAllRaidTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RaidTarget{}
	for rows.Next() {
		var i RaidTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNorm,
			&i.Zone,
			&i.ZoneNorm,
			&i.Expansion,
			&i.Category,
			&i.IsQuakeTarget,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRaidTargets = `-- name: ListRaidTargets :many
SELECT id, name, name_norm, zone, zone_norm, expansion, category, is_quake_target, state, created_at, updated_at FROM raid_target WHERE state = ?1 ORDER BY name_norm
`

func (q *Queries) ListRaidTargets(ctx context.Context, state string) ([]RaidTarget, error) {
	rows, err := q.db.QueryContext(ctx, listRaidTargets, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RaidTarget{}
	for rows.Next() {
		var i RaidTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNorm,
			&i.Zone,
			&i.ZoneNorm,
			&i.Expansion,
			&i.Category,
			&i.IsQuakeTarget,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRaidTarget = `-- name: UpdateRaidTarget :one
UPDATE raid_target
SET name = ?1, name_norm = ?2,
    zone = ?3, zone_norm = ?4,
    expansion = ?5, category = ?6,
    is_quake_target = ?7, state = ?8,
    updated_at = ?9
WHERE id = ?10
RETURNING id, name, name_norm, zone, zone_norm, expansion, category, is_quake_target, state, created_at, updated_at
`

type UpdateRaidTargetParams struct {
	Name          string
	NameNorm      string
	Zone          string
	ZoneNorm      string
	Expansion     string
	Category      string
	IsQuakeTarget int64
	State         string
	UpdatedAt     int64
	ID            string
}

func (q *Queries) UpdateRaidTarget(ctx context.Context, arg UpdateRaidTargetParams) (RaidTarget, error) {
	row := q.db.QueryRowContext(ctx, updateRaidTarget,
		arg.Name,
		arg.NameNorm,
		arg.Zone,
		arg.ZoneNorm,
		arg.Expansion,
		arg.Category,
		arg.IsQuakeTarget,
		arg.State,
		arg.UpdatedAt,
		arg.ID,
	)
	var i RaidTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNorm,
		&i.Zone,
		&i.ZoneNorm,
		&i.Expansion,
		&i.Category,
		&i.IsQuakeTarget,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
