// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raid_target_timer.sql

package sqlitegen

import (
	"context"
)

const getRaidTargetTimer = `-- name: GetRaidTargetTimer :one
SELECT target_id, server, window_kind, window_open_offset_seconds, window_close_offset_seconds, fixed_grace_seconds, cluster_epsilon_seconds, source, note, created_at, updated_at FROM raid_target_timer
WHERE target_id = ?1 AND server = ?2
`

type GetRaidTargetTimerParams struct {
	TargetID string
	Server   string
}

func (q *Queries) GetRaidTargetTimer(ctx context.Context, arg GetRaidTargetTimerParams) (RaidTargetTimer, error) {
	row := q.db.QueryRowContext(ctx, getRaidTargetTimer, arg.TargetID, arg.Server)
	var i RaidTargetTimer
	err := row.Scan(
		&i.TargetID,
		&i.Server,
		&i.WindowKind,
		&i.WindowOpenOffsetSeconds,
		&i.WindowCloseOffsetSeconds,
		&i.FixedGraceSeconds,
		&i.ClusterEpsilonSeconds,
		&i.Source,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRaidTargetTimersForServer = `-- name: ListRaidTargetTimersForServer :many
SELECT target_id, server, window_kind, window_open_offset_seconds, window_close_offset_seconds, fixed_grace_seconds, cluster_epsilon_seconds, source, note, created_at, updated_at FROM raid_target_timer WHERE server = ?1 ORDER BY target_id
`

func (q *Queries) ListRaidTargetTimersForServer(ctx context.Context, server string) ([]RaidTargetTimer, error) {
	rows, err := q.db.QueryContext(ctx, listRaidTargetTimersForServer, server)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RaidTargetTimer{}
	for rows.Next() {
		var i RaidTargetTimer
		if err := rows.Scan(
			&i.TargetID,
			&i.Server,
			&i.WindowKind,
			&i.WindowOpenOffsetSeconds,
			&i.WindowCloseOffsetSeconds,
			&i.FixedGraceSeconds,
			&i.ClusterEpsilonSeconds,
			&i.Source,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putRaidTargetTimer = `-- name: PutRaidTargetTimer :one

INSERT INTO raid_target_timer (
  target_id, server, window_kind, window_open_offset_seconds, window_close_offset_seconds,
  fixed_grace_seconds, cluster_epsilon_seconds, source, note, created_at, updated_at
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5,
  ?6, ?7, ?8,
  ?9, ?10, ?11
)
ON CONFLICT (target_id, server) DO UPDATE SET
  window_kind = excluded.window_kind,
  window_open_offset_seconds = excluded.window_open_offset_seconds,
  window_close_offset_seconds = excluded.window_close_offset_seconds,
  fixed_grace_seconds = excluded.fixed_grace_seconds,
  cluster_epsilon_seconds = excluded.cluster_epsilon_seconds,
  source = excluded.source,
  note = excluded.note,
  updated_at = excluded.updated_at
RETURNING target_id, server, window_kind, window_open_offset_seconds, window_close_offset_seconds, fixed_grace_seconds, cluster_epsilon_seconds, source, note, created_at, updated_at
`

type PutRaidTargetTimerParams struct {
	TargetID                 string
	Server                   string
	WindowKind               string
	WindowOpenOffsetSeconds  *int64
	WindowCloseOffsetSeconds *int64
	FixedGraceSeconds        int64
	ClusterEpsilonSeconds    *int64
	Source                   *string
	Note                     string
	CreatedAt                int64
	UpdatedAt                int64
}

// raid_target_timer - the per-server respawn window. These numbers do not ship; they load from the
// separate tod-serve-p99-seed repository, and an unseeded instance reports no_timer.
func (q *Queries) PutRaidTargetTimer(ctx context.Context, arg PutRaidTargetTimerParams) (RaidTargetTimer, error) {
	row := q.db.QueryRowContext(ctx, putRaidTargetTimer,
		arg.TargetID,
		arg.Server,
		arg.WindowKind,
		arg.WindowOpenOffsetSeconds,
		arg.WindowCloseOffsetSeconds,
		arg.FixedGraceSeconds,
		arg.ClusterEpsilonSeconds,
		arg.Source,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RaidTargetTimer
	err := row.Scan(
		&i.TargetID,
		&i.Server,
		&i.WindowKind,
		&i.WindowOpenOffsetSeconds,
		&i.WindowCloseOffsetSeconds,
		&i.FixedGraceSeconds,
		&i.ClusterEpsilonSeconds,
		&i.Source,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
