// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_revocation.sql

package sqlitegen

import (
	"context"
)

const countSessionRevocations = `-- name: CountSessionRevocations :one
SELECT COUNT(*) FROM session_revocation WHERE session_id = ?1
`

// Asked on every session-authenticated request, by primary key. A count rather than the row: the
// only question is whether this session was signed out, so nothing else is worth selecting.
func (q *Queries) CountSessionRevocations(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionRevocations, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredSessionRevocations = `-- name: DeleteExpiredSessionRevocations :execrows
DELETE FROM session_revocation WHERE expires_at < ?1
`

// A revocation stops meaning anything once the session it names has expired, because the codec
// refuses an expired cookie on its own.
func (q *Queries) DeleteExpiredSessionRevocations(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessionRevocations, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeSession = `-- name: RevokeSession :exec

INSERT INTO session_revocation (session_id, expires_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (session_id) DO UPDATE SET updated_at = excluded.updated_at
`

type RevokeSessionParams struct {
	SessionID string
	ExpiresAt int64
	CreatedAt int64
	UpdatedAt int64
}

// session_revocation - browser sessions that have signed out. A session is signed rather than
// stored, so this table holds only the ones somebody ended, and only until they would have expired.
//
// Instance-scoped (canonical section 9): a session id is instance-unique and the row names no
// circle. Every route passes the CALLER'S OWN session id, read off the verified cookie.
// Signing out twice is one row, not an error: there is one fact to record, and a second sign-out
// of an already-ended session must not fail. The retry moves updated_at and nothing else, so
// created_at stays the moment the session actually stopped working.
func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession,
		arg.SessionID,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
