// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: target_state_cache.sql

package sqlitegen

import (
	"context"
)

const getTargetState = `-- name: GetTargetState :one
SELECT circle_id, target_id, computed_at, latest_report_id, report_count, status, confidence, contested, contest_reason, change_reason, died_at, window_open_at, window_close_at, spawn_at, distinct_reporter_count, log_line_count, spread_seconds, revoked_reporter_count, created_at, updated_at FROM target_state_cache
WHERE circle_id = ?1 AND target_id = ?2
`

type GetTargetStateParams struct {
	CircleID string
	TargetID string
}

func (q *Queries) GetTargetState(ctx context.Context, arg GetTargetStateParams) (TargetStateCache, error) {
	row := q.db.QueryRowContext(ctx, getTargetState, arg.CircleID, arg.TargetID)
	var i TargetStateCache
	err := row.Scan(
		&i.CircleID,
		&i.TargetID,
		&i.ComputedAt,
		&i.LatestReportID,
		&i.ReportCount,
		&i.Status,
		&i.Confidence,
		&i.Contested,
		&i.ContestReason,
		&i.ChangeReason,
		&i.DiedAt,
		&i.WindowOpenAt,
		&i.WindowCloseAt,
		&i.SpawnAt,
		&i.DistinctReporterCount,
		&i.LogLineCount,
		&i.SpreadSeconds,
		&i.RevokedReporterCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const invalidateCircleTargetStates = `-- name: InvalidateCircleTargetStates :execrows
DELETE FROM target_state_cache WHERE circle_id = ?1
`

// What a quake, a timer change or `tod-serve rebuild-states` does to a whole circle.
func (q *Queries) InvalidateCircleTargetStates(ctx context.Context, circleID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, invalidateCircleTargetStates, circleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const invalidateTargetState = `-- name: InvalidateTargetState :execrows
DELETE FROM target_state_cache
WHERE circle_id = ?1 AND target_id = ?2
`

type InvalidateTargetStateParams struct {
	CircleID string
	TargetID string
}

// Invalidation is a DELETE, not a flag: a stale row with a "stale" bit is still a row somebody
// reads by accident, and this table is droppable by construction.
func (q *Queries) InvalidateTargetState(ctx context.Context, arg InvalidateTargetStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, invalidateTargetState, arg.CircleID, arg.TargetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTargetStates = `-- name: ListTargetStates :many
SELECT circle_id, target_id, computed_at, latest_report_id, report_count, status, confidence, contested, contest_reason, change_reason, died_at, window_open_at, window_close_at, spawn_at, distinct_reporter_count, log_line_count, spread_seconds, revoked_reporter_count, created_at, updated_at FROM target_state_cache
WHERE circle_id = ?1
ORDER BY window_open_at, target_id
`

func (q *Queries) ListTargetStates(ctx context.Context, circleID string) ([]TargetStateCache, error) {
	rows, err := q.db.QueryContext(ctx, listTargetStates, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TargetStateCache{}
	for rows.Next() {
		var i TargetStateCache
		if err := rows.Scan(
			&i.CircleID,
			&i.TargetID,
			&i.ComputedAt,
			&i.LatestReportID,
			&i.ReportCount,
			&i.Status,
			&i.Confidence,
			&i.Contested,
			&i.ContestReason,
			&i.ChangeReason,
			&i.DiedAt,
			&i.WindowOpenAt,
			&i.WindowCloseAt,
			&i.SpawnAt,
			&i.DistinctReporterCount,
			&i.LogLineCount,
			&i.SpreadSeconds,
			&i.RevokedReporterCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putTargetState = `-- name: PutTargetState :one

INSERT INTO target_state_cache (
  circle_id, target_id, computed_at, latest_report_id, report_count, status, confidence,
  contested, contest_reason, change_reason, died_at, window_open_at, window_close_at, spawn_at,
  distinct_reporter_count, log_line_count, spread_seconds, revoked_reporter_count,
  created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8,
  ?9, ?10, ?11,
  ?12, ?13, ?14,
  ?15, ?16, ?17,
  ?18, ?19, ?20
)
ON CONFLICT (circle_id, target_id) DO UPDATE SET
  computed_at = excluded.computed_at,
  latest_report_id = excluded.latest_report_id,
  report_count = excluded.report_count,
  status = excluded.status,
  confidence = excluded.confidence,
  contested = excluded.contested,
  contest_reason = excluded.contest_reason,
  change_reason = excluded.change_reason,
  died_at = excluded.died_at,
  window_open_at = excluded.window_open_at,
  window_close_at = excluded.window_close_at,
  spawn_at = excluded.spawn_at,
  distinct_reporter_count = excluded.distinct_reporter_count,
  log_line_count = excluded.log_line_count,
  spread_seconds = excluded.spread_seconds,
  revoked_reporter_count = excluded.revoked_reporter_count,
  updated_at = excluded.updated_at
RETURNING circle_id, target_id, computed_at, latest_report_id, report_count, status, confidence, contested, contest_reason, change_reason, died_at, window_open_at, window_close_at, spawn_at, distinct_reporter_count, log_line_count, spread_seconds, revoked_reporter_count, created_at, updated_at
`

type PutTargetStateParams struct {
	CircleID              string
	TargetID              string
	ComputedAt            int64
	LatestReportID        *string
	ReportCount           int64
	Status                string
	Confidence            string
	Contested             int64
	ContestReason         *string
	ChangeReason          *string
	DiedAt                *int64
	WindowOpenAt          *int64
	WindowCloseAt         *int64
	SpawnAt               *int64
	DistinctReporterCount int64
	LogLineCount          int64
	SpreadSeconds         *int64
	RevokedReporterCount  int64
	CreatedAt             int64
	UpdatedAt             int64
}

// target_state_cache - materialised consensus, and NEVER authority. Every row here is droppable;
// if you find yourself reading it to make a decision the derivation should make, that is the bug.
func (q *Queries) PutTargetState(ctx context.Context, arg PutTargetStateParams) (TargetStateCache, error) {
	row := q.db.QueryRowContext(ctx, putTargetState,
		arg.CircleID,
		arg.TargetID,
		arg.ComputedAt,
		arg.LatestReportID,
		arg.ReportCount,
		arg.Status,
		arg.Confidence,
		arg.Contested,
		arg.ContestReason,
		arg.ChangeReason,
		arg.DiedAt,
		arg.WindowOpenAt,
		arg.WindowCloseAt,
		arg.SpawnAt,
		arg.DistinctReporterCount,
		arg.LogLineCount,
		arg.SpreadSeconds,
		arg.RevokedReporterCount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TargetStateCache
	err := row.Scan(
		&i.CircleID,
		&i.TargetID,
		&i.ComputedAt,
		&i.LatestReportID,
		&i.ReportCount,
		&i.Status,
		&i.Confidence,
		&i.Contested,
		&i.ContestReason,
		&i.ChangeReason,
		&i.DiedAt,
		&i.WindowOpenAt,
		&i.WindowCloseAt,
		&i.SpawnAt,
		&i.DistinctReporterCount,
		&i.LogLineCount,
		&i.SpreadSeconds,
		&i.RevokedReporterCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
