// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tod_meta.sql

package sqlitegen

import (
	"context"
)

const getMeta = `-- name: GetMeta :one

SELECT "key", value, updated_at FROM tod_meta WHERE key = ?1
`

// tod_meta - instance key/value: schema version, pepper generation, event head.
func (q *Queries) GetMeta(ctx context.Context, key string) (TodMeta, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var i TodMeta
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const setMeta = `-- name: SetMeta :exec
INSERT INTO tod_meta (key, value, updated_at)
VALUES (?1, ?2, ?3)
ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type SetMetaParams struct {
	Key       string
	Value     string
	UpdatedAt int64
}

func (q *Queries) SetMeta(ctx context.Context, arg SetMetaParams) error {
	_, err := q.db.ExecContext(ctx, setMeta, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
