// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tod_report.sql

package sqlitegen

import (
	"context"
)

const createTodReport = `-- name: CreateTodReport :one

INSERT INTO tod_report (
  id, circle_id, target_id, kind, died_at, reported_at, reporter_membership_id, source,
  self_confidence, source_line, source_character, log_character, killed_by_guild,
  client_clock_offset_seconds, retracts_report_id
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8,
  ?9, ?10, ?11,
  ?12, ?13, ?14,
  ?15
)
RETURNING id, circle_id, target_id, kind, died_at, reported_at, reporter_membership_id, source, self_confidence, source_line, source_character, log_character, killed_by_guild, client_clock_offset_seconds, retracts_report_id
`

type CreateTodReportParams struct {
	ID                       string
	CircleID                 string
	TargetID                 string
	Kind                     string
	DiedAt                   int64
	ReportedAt               int64
	ReporterMembershipID     string
	Source                   string
	SelfConfidence           string
	SourceLine               *string
	SourceCharacter          *string
	LogCharacter             *string
	KilledByGuild            *string
	ClientClockOffsetSeconds *int64
	RetractsReportID         *string
}

// tod_report - APPEND-ONLY, the core log. There is no UPDATE and no DELETE here, in Go, in SQL or
// in a migration: corrections are new rows and a retraction is a row with retracts_report_id set.
// The triggers abort anything else.
func (q *Queries) CreateTodReport(ctx context.Context, arg CreateTodReportParams) (TodReport, error) {
	row := q.db.QueryRowContext(ctx, createTodReport,
		arg.ID,
		arg.CircleID,
		arg.TargetID,
		arg.Kind,
		arg.DiedAt,
		arg.ReportedAt,
		arg.ReporterMembershipID,
		arg.Source,
		arg.SelfConfidence,
		arg.SourceLine,
		arg.SourceCharacter,
		arg.LogCharacter,
		arg.KilledByGuild,
		arg.ClientClockOffsetSeconds,
		arg.RetractsReportID,
	)
	var i TodReport
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.TargetID,
		&i.Kind,
		&i.DiedAt,
		&i.ReportedAt,
		&i.ReporterMembershipID,
		&i.Source,
		&i.SelfConfidence,
		&i.SourceLine,
		&i.SourceCharacter,
		&i.LogCharacter,
		&i.KilledByGuild,
		&i.ClientClockOffsetSeconds,
		&i.RetractsReportID,
	)
	return i, err
}

const getRetractionForReport = `-- name: GetRetractionForReport :one
SELECT id, circle_id, target_id, kind, died_at, reported_at, reporter_membership_id, source, self_confidence, source_line, source_character, log_character, killed_by_guild, client_clock_offset_seconds, retracts_report_id FROM tod_report
WHERE circle_id = ?1 AND retracts_report_id = ?2
`

type GetRetractionForReportParams struct {
	CircleID         string
	RetractsReportID *string
}

func (q *Queries) GetRetractionForReport(ctx context.Context, arg GetRetractionForReportParams) (TodReport, error) {
	row := q.db.QueryRowContext(ctx, getRetractionForReport, arg.CircleID, arg.RetractsReportID)
	var i TodReport
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.TargetID,
		&i.Kind,
		&i.DiedAt,
		&i.ReportedAt,
		&i.ReporterMembershipID,
		&i.Source,
		&i.SelfConfidence,
		&i.SourceLine,
		&i.SourceCharacter,
		&i.LogCharacter,
		&i.KilledByGuild,
		&i.ClientClockOffsetSeconds,
		&i.RetractsReportID,
	)
	return i, err
}

const getTodReport = `-- name: GetTodReport :one
SELECT id, circle_id, target_id, kind, died_at, reported_at, reporter_membership_id, source, self_confidence, source_line, source_character, log_character, killed_by_guild, client_clock_offset_seconds, retracts_report_id FROM tod_report WHERE circle_id = ?1 AND id = ?2
`

type GetTodReportParams struct {
	CircleID string
	ID       string
}

func (q *Queries) GetTodReport(ctx context.Context, arg GetTodReportParams) (TodReport, error) {
	row := q.db.QueryRowContext(ctx, getTodReport, arg.CircleID, arg.ID)
	var i TodReport
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.TargetID,
		&i.Kind,
		&i.DiedAt,
		&i.ReportedAt,
		&i.ReporterMembershipID,
		&i.Source,
		&i.SelfConfidence,
		&i.SourceLine,
		&i.SourceCharacter,
		&i.LogCharacter,
		&i.KilledByGuild,
		&i.ClientClockOffsetSeconds,
		&i.RetractsReportID,
	)
	return i, err
}

const getTodReportByNaturalKey = `-- name: GetTodReportByNaturalKey :one
SELECT id, circle_id, target_id, kind, died_at, reported_at, reporter_membership_id, source, self_confidence, source_line, source_character, log_character, killed_by_guild, client_clock_offset_seconds, retracts_report_id FROM tod_report
WHERE circle_id = ?1
  AND target_id = ?2
  AND reporter_membership_id = ?3
  AND died_at = ?4
  AND kind = 'kill'
`

type GetTodReportByNaturalKeyParams struct {
	CircleID             string
	TargetID             string
	ReporterMembershipID string
	DiedAt               int64
}

// The second line of defence behind Idempotency-Key: the same reporter cannot lodge the same kill
// twice even if the header is botched. A duplicate is a replay - 200 with the existing report.
func (q *Queries) GetTodReportByNaturalKey(ctx context.Context, arg GetTodReportByNaturalKeyParams) (TodReport, error) {
	row := q.db.QueryRowContext(ctx, getTodReportByNaturalKey,
		arg.CircleID,
		arg.TargetID,
		arg.ReporterMembershipID,
		arg.DiedAt,
	)
	var i TodReport
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.TargetID,
		&i.Kind,
		&i.DiedAt,
		&i.ReportedAt,
		&i.ReporterMembershipID,
		&i.Source,
		&i.SelfConfidence,
		&i.SourceLine,
		&i.SourceCharacter,
		&i.LogCharacter,
		&i.KilledByGuild,
		&i.ClientClockOffsetSeconds,
		&i.RetractsReportID,
	)
	return i, err
}

const listTodReportTargets = `-- name: ListTodReportTargets :many
SELECT DISTINCT target_id FROM tod_report
WHERE circle_id = ?1
ORDER BY target_id
`

// Every target this circle has reported anything about. It is what makes a read-miss rebuild
// bounded by the circle's activity rather than by the catalogue: a target nobody has reported has
// no cluster to derive and nothing worth a cache row, so the board answers it without a read.
func (q *Queries) ListTodReportTargets(ctx context.Context, circleID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTodReportTargets, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var target_id string
		if err := rows.Scan(&target_id); err != nil {
			return nil, err
		}
		items = append(items, target_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodReports = `-- name: ListTodReports :many
SELECT r.id, r.circle_id, r.target_id, r.kind, r.died_at, r.reported_at, r.reporter_membership_id, r.source, r.self_confidence, r.source_line, r.source_character, r.log_character, r.killed_by_guild, r.client_clock_offset_seconds, r.retracts_report_id,
       EXISTS (SELECT 1 FROM tod_report x
               WHERE x.circle_id = r.circle_id AND x.retracts_report_id = r.id) AS retracted
FROM tod_report r
WHERE r.circle_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR r.id < ?2)
  AND (CAST(?3 AS TEXT) IS NULL OR r.target_id = ?3)
  AND (CAST(?4 AS INTEGER) IS NULL OR r.died_at >= ?4)
  AND (CAST(?5 AS INTEGER) IS NULL OR r.died_at <= ?5)
  AND (CAST(?6 AS TEXT) IS NULL
       OR r.reporter_membership_id = ?6)
  AND (CAST(?7 AS INTEGER) = 1
       OR (r.kind = 'kill'
           AND NOT EXISTS (SELECT 1 FROM tod_report x
                           WHERE x.circle_id = r.circle_id AND x.retracts_report_id = r.id)))
ORDER BY r.id DESC
LIMIT ?8
`

type ListTodReportsParams struct {
	CircleID             string
	AfterID              string
	TargetID             *string
	DiedAfter            *int64
	DiedBefore           *int64
	ReporterMembershipID *string
	IncludeRetracted     int64
	RowLimit             int64
}

type ListTodReportsRow struct {
	ID                       string
	CircleID                 string
	TargetID                 string
	Kind                     string
	DiedAt                   int64
	ReportedAt               int64
	ReporterMembershipID     string
	Source                   string
	SelfConfidence           string
	SourceLine               *string
	SourceCharacter          *string
	LogCharacter             *string
	KilledByGuild            *string
	ClientClockOffsetSeconds *int64
	RetractsReportID         *string
	Retracted                bool
}

// The report log, newest first. The id is a ULID, so it is also the cursor: time-ordered, opaque
// and free, and an empty cursor is the first page rather than a sentinel a caller has to know.
//
// `retracted` is computed rather than stored, because the retraction is a SEPARATE ROW and the
// original is never touched. `include_retracted = 0` hides a retracted kill AND every retraction
// row: a retraction the caller can see pointing at a report they cannot is a dangling reference
// the client would have to explain.
func (q *Queries) ListTodReports(ctx context.Context, arg ListTodReportsParams) ([]ListTodReportsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodReports,
		arg.CircleID,
		arg.AfterID,
		arg.TargetID,
		arg.DiedAfter,
		arg.DiedBefore,
		arg.ReporterMembershipID,
		arg.IncludeRetracted,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodReportsRow{}
	for rows.Next() {
		var i ListTodReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.TargetID,
			&i.Kind,
			&i.DiedAt,
			&i.ReportedAt,
			&i.ReporterMembershipID,
			&i.Source,
			&i.SelfConfidence,
			&i.SourceLine,
			&i.SourceCharacter,
			&i.LogCharacter,
			&i.KilledByGuild,
			&i.ClientClockOffsetSeconds,
			&i.RetractsReportID,
			&i.Retracted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodReportsForCircle = `-- name: ListTodReportsForCircle :many
SELECT id, circle_id, target_id, kind, died_at, reported_at, reporter_membership_id, source, self_confidence, source_line, source_character, log_character, killed_by_guild, client_clock_offset_seconds, retracts_report_id FROM tod_report
WHERE circle_id = ?1
ORDER BY target_id, died_at, id
`

// Every report in the circle, grouped by target, for `tod-serve rebuild-states` and the nightly
// verify job. One query rather than one per target: a rebuild that issued a query per target would
// be the slowest thing the binary does, and it runs on a schedule nobody watches.
func (q *Queries) ListTodReportsForCircle(ctx context.Context, circleID string) ([]TodReport, error) {
	rows, err := q.db.QueryContext(ctx, listTodReportsForCircle, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodReport{}
	for rows.Next() {
		var i TodReport
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.TargetID,
			&i.Kind,
			&i.DiedAt,
			&i.ReportedAt,
			&i.ReporterMembershipID,
			&i.Source,
			&i.SelfConfidence,
			&i.SourceLine,
			&i.SourceCharacter,
			&i.LogCharacter,
			&i.KilledByGuild,
			&i.ClientClockOffsetSeconds,
			&i.RetractsReportID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodReportsForTarget = `-- name: ListTodReportsForTarget :many
SELECT id, circle_id, target_id, kind, died_at, reported_at, reporter_membership_id, source, self_confidence, source_line, source_character, log_character, killed_by_guild, client_clock_offset_seconds, retracts_report_id FROM tod_report
WHERE circle_id = ?1 AND target_id = ?2
ORDER BY died_at, id
`

type ListTodReportsForTargetParams struct {
	CircleID string
	TargetID string
}

// Everything the derivation needs for one target, including retractions: consensus folds them, the
// store does not, because a store that dropped rows would decide what counts as evidence.
func (q *Queries) ListTodReportsForTarget(ctx context.Context, arg ListTodReportsForTargetParams) ([]TodReport, error) {
	rows, err := q.db.QueryContext(ctx, listTodReportsForTarget, arg.CircleID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodReport{}
	for rows.Next() {
		var i TodReport
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.TargetID,
			&i.Kind,
			&i.DiedAt,
			&i.ReportedAt,
			&i.ReporterMembershipID,
			&i.Source,
			&i.SelfConfidence,
			&i.SourceLine,
			&i.SourceCharacter,
			&i.LogCharacter,
			&i.KilledByGuild,
			&i.ClientClockOffsetSeconds,
			&i.RetractsReportID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
